"""Round 15 corp kits: every slice type a corp uses, with its full-background animation (label, loop text)."""
KIT = {  # (program, value, special, scene_kind override, label, loop description)
    "meridian": [
        ("EXPLOIT", 14, None, None, "ATTACK", "crates ride the rollers past the screen (kept)"),
        ("ZERO-DAY", 24, None, None, "CRIT", "laser sweeps the big barcode, PRIORITY stamp slams down (kept)"),
        ("FIREWALL", 12, None, None, "DEFEND", "a crane lowers a container onto the container wall"),
        ("SANDBOX", 8, None, None, "SHIELD", "the box lid folds shut, then tape is pulled across"),
        ("VIRUS", 3, "tariff", None, "JUDGEMENT (RAM drain)", "a gavel strikes the block: flash and shockwave"),
        ("NULL", None, None, None, "MISS", "the box falls open: sides drop, nothing inside"),
    ],
    "solace": [
        ("EXPLOIT", 14, None, None, "ATTACK", "angled syringe, plunger pushes, liquid drips off the needle"),
        ("ZERO-DAY", 24, None, None, "CRIT", "a heartbeat pulse races across the screen"),
        ("FIREWALL", 12, None, None, "DEFEND", "a beaker pours into a vial; the vial fills"),
        ("PATCH", 4, None, None, "GROWTH (heal)", "one cell divides into two (renamed: game name change pending)"),
        ("VIRUS", None, "dose", None, "DOSE", "a pill bottle tips over and pills spill out"),
        ("NULL", None, None, None, "MISS", "flatline; a bright dot travels along it"),
        ("SANDBOX", 5, None, None, "SHIELD", "membrane rings inflate round a cell"),
    ],
    "halcyon": [
        ("EXPLOIT", 14, None, None, "ATTACK", "handcuffs close on a wrist"),
        ("ZERO-DAY", 24, None, None, "CRIT", "a jail door slams shut: CLANG"),
        ("SANDBOX", 8, None, None, "SHIELD", "a thrown rock bounces off a riot shield"),
        ("FIREWALL", 6, None, None, "DEFEND", "police barricades slide together (my pick, not briefed)"),
        ("PATCH", 6, None, None, "HEAL", "an ambulance drives by, lights flashing"),
        ("VIRUS", None, "citation", None, "CITATION", "a paper is stamped FINE"),
        ("NULL", None, None, None, "MISS  option A", "CLOSED sign swings on its chain"),
        ("NULL", None, None, "MISS_B", "MISS  option B", "an empty file folder flops open: NO RECORD"),
    ],
    "orbital": [
        ("EXPLOIT", 14, None, None, "ATTACK", "one small meteor hits the planet"),
        ("ZERO-DAY", 24, None, None, "CRIT", "a large meteor and a shower of small ones hit"),
        ("FIREWALL", 12, None, None, "DEFEND", "a satellite laser destroys a meteor"),
        ("PROXY", 1, None, None, "EVADE", "a spaceship fires its engine and leaves the screen"),
        ("VIRUS", None, "solar_flare", None, "SOLAR FLARE", "corona turns, a flare loop erupts (kept)"),
        ("NULL", None, None, None, "MISS", "an astronaut drifts off into space: TETHER LOST"),
        ("SANDBOX", 8, None, None, "SHIELD", "an energy dome pulses over the planet"),
        ("PATCH", 6, None, None, "HEAL", "a satellite unfolds its solar panels"),
    ],
    "rebel_cell": [
        ("EXPLOIT", 14, None, None, "ATTACK", "the player's EXPLOIT screen, in red"),
        ("ZERO-DAY", 24, None, None, "CRIT", "the player's ZERO-DAY skull, in red"),
        ("FIREWALL", 12, None, None, "DEFEND", "the player's FIREWALL, in red"),
        ("SANDBOX", 5, None, None, "SHIELD", "the player's SANDBOX PCB, in red"),
        ("PROXY", 1, None, None, "EVADE", "the player's PROXY detour, in red"),
        ("VIRUS", 3, None, None, "AFFLICT", "the player's VIRUS ooze, in red"),
        ("PATCH", 6, None, None, "HEAL", "the player's PATCH, in red"),
        ("NULL", None, None, None, "MISS", "the player's NULL, in red"),
    ],
}
