"""Art pass W8a: writes the baked vector art (ART_BIBLE 4.3 rule 5, 11 Title, 3.6).

    python tools/art/w8a_svgs.py

Deterministic (no randomness: a fixed integer hash jitters the hand-made shapes), original
letterforms drawn as paths (no font is embedded), so the art never changes with the
language and never needs a font at runtime:

- assets/art/logo_rebel_cell.svg      the REBEL_CELL drip-graffiti logo, CELL_PINK + INK
- assets/art/scrawl_never_sleep.svg   the NEVER / SLEEP marker scrawl with the crown doodle
- assets/art/scrawl_trust_no_one.svg  the TRUST / NO ONE marker scrawl
- assets/art/landmarks/<corp>.svg     each corporation's landmark glyph (ART_BIBLE 3.6), white
                                      strokes on clear, tinted in the corp hue at runtime

It also prints the logo's drip ends (normalised), which LogoArt.DRIP_ENDS mirrors.
Written as a file on purpose: never run Python from stdin on this machine.
"""

from __future__ import annotations

import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ART = ROOT / "assets" / "art"

CELL_PINK = "#FF3DA8"
INK = "#111111"
PAPER = "#F2EEE4"
WHITE = "#FFFFFF"


def jit(n: int, salt: int, amp: float) -> float:
    """A fixed hash in [-amp, amp] (the same every run)."""
    h = (n * 2654435761 + salt * 40503) & 0xFFFFFFFF
    h ^= h >> 13
    h = (h * 1274126177) & 0xFFFFFFFF
    return ((h & 0xFFFF) / 0xFFFF * 2.0 - 1.0) * amp


# --- Logo: block drip letters -------------------------------------------------------------------
# Each letter on an 80-unit-tall grid: (width, path d). Counters use evenodd.
LETTERS = {
    "R": (58, "M0 0 H44 L56 12 V34 L46 44 L60 80 H39 L29 50 H19 V80 H0 Z M19 16 H37 V34 H19 Z"),
    "E": (52, "M0 0 H52 V18 H19 V31 H44 V49 H19 V62 H52 V80 H0 Z"),
    "B": (57, "M0 0 H44 L56 12 V31 L48 40 L57 49 V68 L45 80 H0 Z M19 16 H37 V32 H19 Z M19 48 H38 V64 H19 Z"),
    "L": (50, "M0 0 H19 V62 H50 V80 H0 Z"),
    "C": (52, "M10 0 H52 V19 H19 V61 H52 V80 H10 L0 70 V10 Z"),
    "_": (46, "M0 66 H46 V80 H0 Z"),
}
WORD = "REBEL_CELL"
GAP = 7.0
PAD = 18.0
SKEW = -9.0  # degrees
# Drips hang from these letters (index in WORD): (x within the letter, length).
DRIPS = {0: [(8, 30)], 2: [(40, 18)], 4: [(10, 40)], 6: [(30, 24)], 8: [(8, 34)], 9: [(38, 20)]}
DRIP_W = 11.0


def logo() -> tuple[str, list[tuple[float, float]]]:
    x = PAD
    groups: list[str] = []
    drips: list[str] = []
    ends: list[tuple[float, float]] = []
    top = PAD
    tan = math.tan(math.radians(SKEW))
    for i, ch in enumerate(WORD):
        w, d = LETTERS[ch]
        rot = jit(i, 1, 3.0)
        dy = jit(i, 2, 3.0)
        cx, cy = x + w / 2.0, top + 40.0
        groups.append(
            f'<path transform="translate({x:.1f} {top + dy:.1f}) rotate({rot:.2f} {w / 2:.1f} 40)" d="{d}"/>'
        )
        for dx, length in DRIPS.get(i, []):
            px = x + dx
            py = top + dy + 80.0 - 2.0
            ex = px + DRIP_W / 2.0
            ey = py + length
            drips.append(
                f'<path d="M{px:.1f} {py:.1f} h{DRIP_W:.1f} v{length - DRIP_W / 2:.1f} '
                f'a{DRIP_W / 2:.1f} {DRIP_W / 2:.1f} 0 0 1 {-DRIP_W:.1f} 0 Z"/>'
            )
            ends.append((ex, ey))
        x += w + GAP
    width = x - GAP + PAD + 80.0 * abs(tan)
    height = top + 80.0 + 46.0 + PAD * 0.5
    skew = f'skewX({SKEW}) translate({80.0 * abs(tan) + 6:.1f} 0)'
    shapes = "\n    ".join(groups + drips)
    # The hard ink shadow, the ink outline, the pink fill, a paper glint on each letter's top.
    glints = "\n    ".join(
        f'<rect x="{PAD + sum(LETTERS[c][0] + GAP for c in WORD[:i]) + 4:.1f}" y="{PAD + 4 + jit(i, 2, 3.0):.1f}" '
        f'width="{LETTERS[ch][0] * 0.35:.1f}" height="3" rx="1.5"/>'
        for i, ch in enumerate(WORD) if ch != "_"
    )
    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{width:.0f}" height="{height:.0f}" viewBox="0 0 {width:.0f} {height:.0f}">
  <!-- REBEL_CELL logo (art pass W8a, ART_BIBLE 11 Title / 4.3 rule 5): original drip-graffiti
       block letters, CELL_PINK fill on an INK outline and hard INK shadow. Generated by
       tools/art/w8a_svgs.py; do not edit by hand. -->
  <g transform="{skew}" fill-rule="evenodd">
   <g fill="{INK}" stroke="{INK}" stroke-width="12" stroke-linejoin="round" transform="translate(5 5)">
    {shapes}
   </g>
   <g fill="{INK}" stroke="{INK}" stroke-width="10" stroke-linejoin="round">
    {shapes}
   </g>
   <g fill="{CELL_PINK}">
    {shapes}
   </g>
   <g fill="{PAPER}" opacity="0.85">
    {glints}
   </g>
  </g>
</svg>
'''
    # Drip ends in the skewed frame, normalised to the image.
    out = []
    for ex, ey in ends:
        sx = ex + 80.0 * abs(tan) + 6 + ey * tan
        out.append((round(sx / width, 4), round(ey / height, 4)))
    return svg, out


# --- Marker scrawls: solid marker letters (skeletons drawn at marker width) ------------------------------------------------------------
STROKES = {
    "N": [[(0, 56), (0, 0), (34, 56), (34, 0)]],
    "E": [[(32, 0), (0, 0), (0, 56), (32, 56)], [(0, 28), (24, 28)]],
    "V": [[(0, 0), (17, 56), (34, 0)]],
    "R": [[(0, 56), (0, 0), (24, 0), (32, 8), (32, 20), (24, 28), (0, 28)], [(14, 28), (34, 56)]],
    "S": [[(32, 4), (24, 0), (8, 0), (0, 8), (0, 20), (8, 28), (26, 28), (34, 36), (34, 48), (26, 56), (8, 56), (0, 50)]],
    "L": [[(0, 0), (0, 56), (30, 56)]],
    "P": [[(0, 56), (0, 0), (24, 0), (32, 8), (32, 20), (24, 28), (0, 28)]],
    "T": [[(0, 0), (36, 0)], [(18, 0), (18, 56)]],
    "U": [[(0, 0), (0, 46), (8, 56), (26, 56), (34, 46), (34, 0)]],
    "O": [[(8, 0), (26, 0), (34, 10), (34, 46), (26, 56), (8, 56), (0, 46), (0, 10), (8, 0)]],
    " ": [],
}
ADV = 47.0
LINE = 74.0


def scrawl(lines: list[str], note: str) -> str:
    """A solid marker/spray scrawl in the logo's drip-graffiti idiom: fat CELL_PINK letterforms
    (the stroke skeletons drawn at marker width, so the letters read filled), an INK keyline
    round each, a hard INK shadow, drips with round bulbs under the last line, a paper glint
    on the first line, and the Cell's crown doodle."""
    k = SCRAWL_SCALE
    strokes: list[str] = []
    drip_paths: list[str] = []
    glints: list[str] = []
    width = 0.0
    n = 0
    last_letters: list[tuple[float, float]] = []
    for li, line in enumerate(lines):
        x = SCRAWL_PAD + li * 20.0
        y = SCRAWL_PAD + li * LINE * k
        row: list[tuple[float, float]] = []
        for ch in line:
            rot = jit(n, 5, 4.0)
            for stroke in STROKES[ch]:
                pts = []
                for pi, (px, py) in enumerate(stroke):
                    pts.append(f"{x + px * k + jit(n * 31 + pi, 7, 1.5):.1f},{y + py * k + jit(n * 17 + pi, 9, 1.5):.1f}")
                strokes.append(f'<polyline transform="rotate({rot:.2f} {x + 17 * k:.1f} {y + 28 * k:.1f})" points="{" ".join(pts)}"/>')
            if ch != " ":
                row.append((x, y))
                if li == 0:
                    glints.append(f'<line x1="{x + 4:.1f}" y1="{y + 3:.1f}" x2="{x + 4 + 12 * k:.1f}" y2="{y + 3:.1f}"/>')
            n += 1
            x += ADV * k + SCRAWL_TRACK if ch != " " else ADV * k * 0.55
        width = max(width, x)
        last_letters = row
    # Drips hang from three letters of the last line (bulb at the end), like the logo's.
    base_y = SCRAWL_PAD + (len(lines) - 1) * LINE * k + 56.0 * k
    bottom = base_y
    for j, (lx, _ly) in enumerate(last_letters[:: max(1, len(last_letters) // 3)][:3]):
        dx = lx + (6.0 + 18.0 * (j % 2)) * k
        length = SCRAWL_DRIPS[j % len(SCRAWL_DRIPS)] * k
        drip_paths.append(f'<path d="M{dx:.1f} {base_y - 4:.1f} v{length:.1f}"/>')
        drip_paths.append(f'<circle cx="{dx:.1f}" cy="{base_y - 4 + length:.1f}" r="{SCRAWL_BULB:.1f}" fill="@FILL@"/>')
        bottom = max(bottom, base_y - 4 + length + SCRAWL_BULB)
    cx = width - 20.0
    cy = base_y + 24.0
    crown = (f'<polygon fill="@FILL@" points="{cx:.1f},{cy:.1f} {cx + 2:.1f},{cy - 14:.1f} {cx + 9:.1f},{cy - 6:.1f} {cx + 15:.1f},{cy - 17:.1f} '
             f'{cx + 21:.1f},{cy - 6:.1f} {cx + 28:.1f},{cy - 14:.1f} {cx + 30:.1f},{cy:.1f}"/>')
    height = max(bottom, cy) + SCRAWL_PAD
    w = width + 30.0
    shapes = "\n    ".join(strokes + drip_paths + [crown])
    gl = "\n    ".join(glints)
    ink_w = SCRAWL_STROKE + 2 * SCRAWL_KEYLINE
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="{w:.0f}" height="{height:.0f}" viewBox="0 0 {w:.0f} {height:.0f}">
  <!-- {note} (art pass W8a, ART_BIBLE 1, 2 PAPER, 4.1, 4.3 rule 5): an original solid marker /
       spray scrawl in the logo's drip-graffiti idiom - CELL_PINK letterforms at marker width
       with an INK keyline, a hard INK shadow, drips with bulbs and the Cell's crown. Generated
       by tools/art/w8a_svgs.py; do not edit by hand. -->
  <g transform="skewX({SCRAWL_SKEW})  translate({abs(math.tan(math.radians(SCRAWL_SKEW))) * height:.1f} 0)" stroke-linecap="round" stroke-linejoin="round">
   <g stroke="{INK}" fill="none" stroke-width="{ink_w:.1f}" transform="translate(5 5)">
    {shapes.replace("@FILL@", INK)}
   </g>
   <g stroke="{INK}" fill="none" stroke-width="{ink_w:.1f}">
    {shapes.replace("@FILL@", INK)}
   </g>
   <g stroke="{CELL_PINK}" fill="none" stroke-width="{SCRAWL_STROKE:.1f}">
    {shapes.replace("@FILL@", CELL_PINK)}
   </g>
   <g stroke="{PAPER}" stroke-width="3" opacity="0.8" fill="none">
    {gl}
   </g>
  </g>
</svg>
'''


# Scrawl proportions: letter scale, marker width, keyline, skew, drip lengths and bulb radius.
SCRAWL_SCALE = 1.2
SCRAWL_STROKE = 9.0
SCRAWL_KEYLINE = 3.0
SCRAWL_SKEW = -7.0
SCRAWL_PAD = 16.0
SCRAWL_DRIPS = [30.0, 18.0, 24.0]
SCRAWL_BULB = 5.5
SCRAWL_TRACK = 7.0


# --- Landmark glyphs (48 x 48, white strokes) ---------------------------------------------------
LANDMARKS = {
    "solace": "DNA helix",
    "meridian": "container crane",
    "halcyon": "clock tower",
    "orbital": "satellite dish",
    "rebel_cell": "inverted Cell hexagon",
}


def helix() -> str:
    a, b = [], []
    for i in range(0, 41, 2):
        y = 4 + i
        a.append(f"{24 + 11 * math.sin(i / 40 * 2 * math.pi):.1f},{y}")
        b.append(f"{24 - 11 * math.sin(i / 40 * 2 * math.pi):.1f},{y}")
    rungs = "".join(
        f'<line x1="{24 + 11 * math.sin(i / 40 * 2 * math.pi):.1f}" y1="{4 + i}" x2="{24 - 11 * math.sin(i / 40 * 2 * math.pi):.1f}" y2="{4 + i}"/>'
        for i in (4, 12, 28, 36)
    )
    return f'<polyline points="{" ".join(a)}"/><polyline points="{" ".join(b)}"/>{rungs}'


GLYPHS = {
    "solace": helix(),
    "meridian": '<polyline points="10,44 10,6 40,6"/><polyline points="10,14 18,6"/><polyline points="4,44 20,44"/>'
                '<polyline points="34,6 34,20"/><rect x="26" y="20" width="16" height="10"/><polyline points="30,20 30,30 M34,20"/>'
                '<line x1="38" y1="20" x2="38" y2="30"/>',
    "halcyon": '<polyline points="14,44 14,18 24,6 34,18 34,44"/><line x1="8" y1="44" x2="40" y2="44"/>'
               '<circle cx="24" cy="24" r="7"/><polyline points="24,19 24,24 28,26"/>',
    "orbital": '<path d="M8 24 A18 18 0 0 0 32 40 Z"/><line x1="20" y1="32" x2="34" y2="16"/><circle cx="36" cy="14" r="3"/>'
               '<polyline points="18,38 14,46 30,46 26,38"/><circle cx="40" cy="6" r="1.5"/><circle cx="8" cy="8" r="1.5"/>',
    "rebel_cell": '<polygon points="24,44 8,35 8,17 24,8 40,17 40,35"/><polyline points="16,20 24,34 32,20"/>',
}


def landmark(corp: str) -> str:
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48">
  <!-- {LANDMARKS[corp]}: the landmark glyph of {corp} (art pass W8a, ART_BIBLE 3.6, 7.4 grammar:
       24 px grid x2, round caps). White, tinted in the corp hue at runtime. -->
  <g fill="none" stroke="{WHITE}" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round">
    {GLYPHS[corp]}
  </g>
</svg>
'''


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    print("wrote", path.relative_to(ROOT))


def main() -> None:
    svg, ends = logo()
    write(ART / "logo_rebel_cell.svg", svg)
    print("DRIP_ENDS", ends)
    write(ART / "scrawl_never_sleep.svg", scrawl(["NEVER", "SLEEP"], "NEVER SLEEP"))
    write(ART / "scrawl_trust_no_one.svg", scrawl(["TRUST", "NO ONE"], "TRUST NO ONE"))
    for corp in LANDMARKS:
        write(ART / "landmarks" / f"{corp}.svg", landmark(corp))


if __name__ == "__main__":
    main()
