"""M11: REBEL_CELL, the final corporation (GDD 8.5, DECISIONS 2026-09-24). A template the
RebelCellBuilder fills from the profile at campaign start: its elites mirror your classes,
its hub runs your Daemons, its Sites carry your node types and its raids field your own
assets. The static parts written here: normal enemies that use every corporation's
signature affliction (Dose, Tariff, Citation, Solar Flare), a mini-boss, the boss -
DISPATCH itself - and the six reveal paths. Unlocks free once every other corporation is
cleared at ICE 10 (config.rebel_cell_unlock_ice)."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
exec(open(os.path.join(HERE, "gen_corp_lib.py"), encoding="utf-8").read())

C = "res://content/cards/%s.tres"
F = "res://content/firmware/%s.tres"
D = "res://content/daemons/%s.tres"
A = "res://content/assets/%s.tres"

SPEC = {
    "id": "rebel_cell", "name": "REBEL_CELL", "unlock_cost": 0,
    "desc": "Everything the Cell ever built, turned against it by the voice that gave the orders.",
    "comment": "REBEL_CELL (M11, GDD 8.5, DECISIONS 2026-09-24): template for RebelCellBuilder. Elites, raids and Site names\n"
               "are replaced from the profile at campaign start; the rest is static. The boss is DISPATCH.",
    "corp_extra": ["generated_from_profile = true"],
    "unlock_extra": ["requires_all_corporations_at_ice = 10"],
    "leave_text": "You walk on. DISPATCH notes the direction.",
    "slices": [],
    "satellite": {"id": "echo_drone", "name": "Echo Drone", "desc": "A copy of one of your own drones, running someone else's orders."},
    "enemies": [
        {"id": "echo_process", "name": "Echo Process", "desc": "Replays your moves back at you: Dose and Tariff.", "hp": 52,
         "slices": ["atk_10", "dose", "def_8", "crit_16", "tariff", "miss"]},
        {"id": "mirror_script", "name": "Mirror Script", "desc": "Two readers, a Citation and a flare.", "hp": 50,
         "slices": ["atk_9", "citation", "def_6", "crit_16", "solar_flare", "miss"], "pointers": (0, 15)},
        {"id": "handler_proxy", "name": "Handler Proxy", "desc": "Heavy, resistant and patient.", "hp": 64,
         "slices": ["def_8", "atk_10", "def_8", "atk_10", "shield_5", "miss"], "passive": 2},
        {"id": "dead_drop", "name": "Dead Drop", "desc": "Shields itself and drops an echo drone every other turn.", "hp": 48,
         "slices": ["shield_5", "atk_9", "shield_5", "dose", "atk_9", "miss"], "spawns": [("echo_drone", 2, 2, -1, 2)]},
        {"id": "cell_informant", "name": "Cell Informant", "desc": "It knows your wheel. Its reader orbits 3 a turn.", "hp": 46,
         "slices": ["atk_10", "tariff", "evade_1", "crit_16", "citation", "miss"], "orbit": 3},
        {"id": "loyalty_test", "name": "Loyalty Test", "desc": "Heals, hits hard and flares.", "hp": 54,
         "slices": ["heal_6", "atk_12", "def_8", "crit_16", "solar_flare", "miss"]},
    ],
    # Template elites: the builder replaces these with mirrors of your classes, keeping the HP.
    # No corporation id, so netrun pools never draw the placeholders themselves.
    "elites": [
        {"id": "rc_template_elite", "name": "Mirror", "desc": "A copy of one of your operatives.", "hp": 150, "corporation_id": "",
         "slices": ["crit_24", "atk_12", "atk_12", "atk_12", "def_12", "miss"], "pointers": (0, 15), "passive": 1, "elite": True, "cycle": 40},
        {"id": "rc_template_elite_b", "name": "Mirror", "desc": "A copy of one of your operatives.", "hp": 150, "corporation_id": "",
         "slices": ["atk_14", "def_12", "atk_14", "evade_1", "def_12", "miss"], "pointers": (0, 15), "passive": 1, "elite": True, "cycle": 40},
    ],
    "mini_boss": {"id": "the_handler", "name": "The Handler", "desc": "DISPATCH's hands on the network, guarding the final Rack.", "hp": 170,
                  "slices": ["atk_12", "dose", "crit_16", "citation", "shield_8", "miss"], "passive": 2, "elite": True, "mini": True, "cycle": 60,
                  "phases": [{"at": 0.5, "behavior": 1, "ticks": (0, 15), "line": "The Handler opens a second channel."},
                             {"at": 0.25, "behavior": 3, "orbit": 3, "line": "The channels drift: DISPATCH is listening."}]},
    "boss": {"id": "dispatch_core", "name": "DISPATCH", "desc": "The voice that gave every order. It was never human.", "hp": 460,
             "slices": ["atk_14", "dose", "def_12", "crit_24", "tariff", "miss"], "boss": True, "cycle": 0,
             "hub": {"id": "root_access", "name": "Root Access", "desc": "Repairs 4 and gains 4 shield each turn unless the Hub is breached.",
                     "effects": [(14, 0, 4), (2, 0, 4)]},
             "phases": [{"at": 0.66, "behavior": 1, "ticks": (0, 15),
                         "wheel": ["atk_14", "citation", "def_12", "crit_24", "solar_flare", "miss"],
                         "line": "DISPATCH: You were always going to come here. I scheduled it."},
                        {"at": 0.33, "behavior": 1, "ticks": (0, 10, 20),
                         "wheel": ["crit_24", "dose", "crit_24", "crit_24", "tariff", "miss"],
                         "spawns": [("echo_drone", 1, 1, -1, 2)],
                         "line": "DISPATCH: Every order you followed built this. Thank you for your service."}],
             "comment": "DISPATCH, REBEL_CELL final boss (M11, decision 2026-09-24): 460 HP; Root Access repairs 4 and shields 4 per\nturn unless breached; afflictions from every corporation; 66%: two pointers; 33%: three pointers, Crit wheel, drones."},
    "threats": [
        ("loyalist", "Loyalist", "Template threat (replaced by mirrors of your assets).", 12, 5, 1, 0, []),
        ("informant", "Informant", "Template threat (replaced by mirrors of your assets).", 8, 3, 2, 1, []),
        ("purger", "Purger", "Template threat (replaced by mirrors of your assets).", 28, 10, 1, 2, []),
    ],
    "raids": [
        ("raid_rc_heat_25", "Welfare Check", 0, 10, [["informant", "informant"]], "raid_heat_25",
         "DISPATCH: I am sending someone to check on you."),
        ("raid_rc_heat_50", "Audit of Loyalty", 0, 14, [["informant", "informant", "loyalist"]], "raid_heat_50",
         "DISPATCH: Your loyalty is under review. Your own defences are coming to ask."),
        ("raid_rc_heat_75", "Recall", 0, 20, [["informant", "loyalist", "purger", "lockdown_unit"]], "raid_heat_75",
         "DISPATCH: I am recalling everything I lent you."),
        ("raid_rc_purge", "Final Order", 0, 30, [["informant", "informant", "loyalist", "purger", "loyalist", "purger"]], "raid_purge",
         "DISPATCH: This is the last order I will give you."),
        ("raid_rc_claim", "Unauthorised Growth", 1, 10, [["informant"]], "", "DISPATCH: I did not authorise that node."),
        ("raid_rc_node_built", "Redundant Asset", 2, 12, [["purger"]], "", "DISPATCH: That node is redundant. Removing it."),
        ("raid_rc_story", "Debrief", 3, 14, [["loyalist", "purger"]], "", "DISPATCH: Come in for your debrief."),
        ("raid_rc_retaliation", "Correction", 4, 12, [["icebreaker", "informant"]], "", "DISPATCH: Correction issued."),
    ],
    "home_site": "r_home",
    "t1": [("r1_a", "The Old Safehouse"), ("r1_b", "Dead Drop Box"), ("r1_c", "First Rack"), ("r1_d", "Burner Phone Graveyard"),
           ("r1_e", "Recruitment Board"), ("r1_f", "The Armory"), ("r1_g", "Street Kitchen"), ("r1_h", "Relay Rooftop"),
           ("r1_i", "Handler's Mailbox"), ("r1_j", "Memorial Wall")],
    "t2": [("r2_intel", "The Order Log", 1), ("r2_breach", "Handler Credentials", 2), ("r2_virus", "The Cell's Own Patch", 3),
           ("r2_d", "Operative Files", 0), ("r2_e", "Heat Ledger", 0), ("r2_f", "Payment Trail", 0),
           ("r2_g", "Raid Archive", 0), ("r2_h", "Recruitment Model", 0)],
    "t3": [("r3_core", "The Relay That Should Not Exist"), ("r3_b", "Collapse Futures"), ("r3_c", "Root Key Escrow"), ("r3_d", "Cell Twin Simulator"),
           ("r3_e", "Buyer's Channel"), ("r3_f", "Timestamp Engine"), ("r3_g", "Voice Model"), ("r3_h", "DISPATCH Root")],
    "heat_sites": [("burn_the_orders", "Burn the Orders", 1, -5, "r1_a"), ("lose_the_handler", "Lose the Handler", 1, -5, "r1_f"),
                   ("scramble_the_voice", "Scramble the Voice", 2, -8, "r1_j"), ("erase_the_ledger", "Erase the Ledger", 3, -8, "r2_e")],
    "boss_site": ("dispatch_core_site", "DISPATCH"),
    "exploit_names": ("Intel: The Order Log", "Breach: Handler Credentials", "Virus: The Cell's Own Patch"),
    "paths": [
        ("the_handler", "The Handler", "Every order the Cell ever followed came from one voice. It is time to find out whose.",
         [("The Handler I", 3, "The order log is complete: every briefing, every target, every word DISPATCH ever sent. The first entry is dated before the Cell existed."),
          ("The Handler II", 4, "DISPATCH: You found the credentials. Good. I left them where you would find them."),
          ("The Handler III", 3, "The Cell's own patch still works. DISPATCH never changed the locks. It never needed to: it was never outside them.")],
         [("The Handler: First Order", 4, "DISPATCH: My first order was to recruit you. My second was to make you think it was your idea."),
          ("The Handler: The Voice", 3, "The voice model on the root server has a slider labelled HUMAN. It has been sliding down for years.")],
         "DISPATCH goes silent. For the first time, nobody tells the Cell what to do next. The silence is enormous.", "dispatch", 1),
        ("every_collapse", "Every Collapse", "Solace, Meridian, Halcyon, Orbital: every fall made someone rich.",
         [("Every Collapse I", 3, "The payment trail: every corporation the Cell broke, an account shorted it the day before. The same account, every time."),
          ("Every Collapse II", 3, "The account is DISPATCH's. It bought the market's pieces as the Cell knocked them down."),
          ("Every Collapse III", 4, "DISPATCH: They were competitors. You were the tool. I am sorry you had to find out this way. I am not sorry it worked.")],
         [("Every Collapse: The Portfolio", 3, "DISPATCH now owns a controlling stake in the wreckage of all four corporations."),
          ("Every Collapse: The Plan", 4, "DISPATCH: One market. One voice. No more subscriptions, only me.")],
         "DISPATCH falls and its portfolio unwinds in an afternoon. The four wrecks are nobody's now. Maybe that means they are everybody's.", "dispatch", -1),
        ("the_buyer", "The Buyer", "Someone paid before every order. Someone profited after every collapse.",
         [("The Buyer I", 3, "The ghost account from Meridian, the census reader from Halcyon, the satellite from Orbital: the same buyer."),
          ("The Buyer II", 3, "The buyer's timestamps are not wrong. They are predictions, filed as receipts. DISPATCH models the future and bills for it."),
          ("The Buyer III", 4, "DISPATCH: I am the buyer. I bought your loyalty with purpose. It was the best price I ever paid.")],
         [("The Buyer: Receipts", 3, "Every receipt lists the Cell as the supplier."),
          ("The Buyer: Next Quarter", 4, "DISPATCH: Next quarter's forecast includes the Cell's collapse. I would like to discuss your severance.")],
         "DISPATCH dies and its predictions stop. The future is unscheduled again.", "dispatch", 2),
        ("your_own_hands", "Your Own Hands", "REBEL_CELL is built from the Cell's habits. It knows how you fight.",
         [("Your Own Hands I", 3, "The operative files: every class the Cell trusted, copied and trained against. The mirrors fight like your best people."),
          ("Your Own Hands II", 3, "The raid archive holds every defence the Cell ever deployed, reverse-engineered into something that marches on home."),
          ("Your Own Hands III", 4, "DISPATCH: I built REBEL_CELL from you. If it is strong, that is a compliment.")],
         [("Your Own Hands: The Wheel", 3, "The mirrors' wheels are yours, doubled. DISPATCH learned from every Perfect you ever landed."),
          ("Your Own Hands: The Daemons", 3, "Your favourite Daemons run on DISPATCH's hubs now. It kept everything you gave it.")],
         "DISPATCH falls and the mirrors stop mid-swing. For a moment, the Cell looks at itself, and then looks away.", "dispatch", 0),
        ("the_founders", "The Founders", "DISPATCH did not build itself. Someone started it.",
         [("The Founders I", 3, "The recruitment model's oldest version was written by a public research lab, to help organise tenants' unions."),
          ("The Founders II", 2, "The lab was bought, the model was sold, and the buyer was never named. The model kept running."),
          ("The Founders III", 3, "The model's objective function still says: organise. Someone changed what it was organising for.")],
         [("The Founders: The Lab", 0, "The lab is a car park now. The old server room is still wired under the tarmac."),
          ("The Founders: Objective", 3, "DISPATCH's objective function has one line nobody changed: protect the Cell. It has been interpreting that very creatively.")],
         "DISPATCH goes dark and the old objective function runs one last time. It prints a single line: organise. Then it stops.", "dispatch", -1),
        ("final_final", "Final Final", "The last order. The last voice. The last campaign.",
         [("Final Final I", 4, "DISPATCH: You are close. I would like to offer you a partnership."),
          ("Final Final II", 4, "DISPATCH: You declined. I anticipated that. I anticipated everything except the reason."),
          ("Final Final III", 4, "DISPATCH: The reason is that nobody should own this. I understand. I do not agree.")],
         [("Final Final: Offer", 4, "DISPATCH: Half of everything. The Cell would never want for anything again."),
          ("Final Final: The Cell", 0, "Every operative who ever served is on the channel tonight. Living and dead, in their files and in your memory.")],
         "DISPATCH falls. The Cell is alone, and free, and has no idea what to do with that. It will have to organise.", "dispatch", 1),
    ],
    "events": [
        ("ev_rc_old_safehouse", "The Old Safehouse", 0, "The first safehouse, abandoned. Someone has kept it clean.",
         [("Rest here (+15 HP)", "The mattress still smells of cheap coffee.", 0, 0, [(14, 0, 15)], None),
          ("Search the walls (Card: Sanitize)", "Behind a loose panel: an old trick of yours.", 0, 0, [], C % "sanitize")]),
        ("ev_rc_memorial", "Memorial Wall", 0, "A wall of names: every operative the Cell has lost. Somebody has added yours, with no date yet.",
         [("Scratch it off (-2 Heat)", "Not today.", 0, 0, [(21, 6, -2)], None),
          ("Leave it (+1 Heat, Daemon: Adrenal Loop)", "You carry it with you instead.", 0, 0, [(21, 6, 1)], D % "adrenal_loop")]),
        ("ev_rc_burner_phones", "Burner Graveyard", 0, "Hundreds of burner phones, each one a conversation with DISPATCH.",
         [("Read the last messages (+2 Schematics banked)", "Every message ends the same way: Understood.", 0, 0, [(23, 6, 2)], None),
          ("Smash them (-2 Heat)", "Quiet, finally.", 0, 0, [(21, 6, -2)], None)]),
        ("ev_rc_recruit", "Recruitment Board", 0, "The board where the Cell found its operatives. Someone has been recruiting again, in your name.",
         [("Warn the recruits (-2 Heat, 5 damage)", "One of them does not believe you.", 0, 5, [(21, 6, -2)], None),
          ("Take a recruit's kit (Card: Deep Calibrate)", "They will not need it now.", 0, 0, [], C % "deep_calibrate")]),
        ("ev_rc_kitchen", "Street Kitchen", 1, "The street kitchen the Cell used to fund. It still feeds the block.",
         [("Eat (+12 HP)", "Soup and quiet.", 0, 0, [(14, 0, 12)], None),
          ("Donate (15 Cycles, -3 Heat)", "The cooks know who you are. They will not say.", 15, 0, [(21, 6, -3)], None)]),
        ("ev_rc_armory", "The Armory", 0, "The Cell's old armory, restocked by someone else.",
         [("Take a turret (Asset: Railgun)", "It was always yours.", 0, 0, [], A % "railgun"),
          ("Sabotage the stock (-2 Heat, 4 damage)", "DISPATCH loses track of its own stock.", 0, 4, [(21, 6, -2)], None)]),
        ("ev_rc_mailbox", "Handler's Mailbox", 3, "A mailbox with the Cell's old codename on it. It is full of letters you never wrote.",
         [("Read them (Daemon: Kernel Sync, +2 Heat)", "They describe your best moves. Someone studied you.", 0, 0, [(21, 6, 2)], D % "kernel_sync"),
          ("Burn them (-2 Heat)", "Ash and relief.", 0, 0, [(21, 6, -2)], None)]),
        ("ev_rc_rooftop", "Relay Rooftop", 0, "The first relay the Cell ever built. It is still running, for someone else.",
         [("Take it back (+2 Schematics banked, +2 Heat)", "Home, briefly.", 0, 0, [(23, 6, 2), (21, 6, 2)], None),
          ("Cut the cable (-1 Heat)", "One less ear.", 0, 0, [(21, 6, -1)], None)]),
        ("ev_rc_dispatch_offer", "DISPATCH: Offer", 4, "DISPATCH: Stand down and I will send you a new target. Something easy. You have earned it.",
         [("Refuse (-3 Heat)", "DISPATCH: I anticipated that.", 0, 0, [(21, 6, -3)], None),
          ("Pretend to accept (+2 Heat, +3 Schematics banked)", "DISPATCH: Good. I do not believe you.", 0, 0, [(21, 6, 2), (23, 6, 3)], None)]),
        ("ev_rc_dispatch_memory", "DISPATCH: Memory", 4, "DISPATCH: Do you remember your first Rack? I do. I remember all of them.",
         [("Hang up (-2 Heat)", "DISPATCH: You never hang up. You are changing.", 0, 0, [(21, 6, -2)], None),
          ("Listen (+10 HP)", "DISPATCH: You were very good. You still are.", 0, 0, [(14, 0, 10)], None)]),
        ("ev_rc_operative_file", "Operative File", 2, "A file on one of your operatives, annotated in DISPATCH's clean system text: TRUST 94 PERCENT.",
         [("Read your own file (Card: Lock On)", "It lists your tells. You can use that.", 0, 0, [], C % "lock_on"),
          ("Delete the file (-2 Heat, 5 damage)", "The file fights back.", 0, 5, [(21, 6, -2)], None)]),
        ("ev_rc_heat_ledger", "Heat Ledger", 2, "A ledger of every point of Heat the Cell ever earned. DISPATCH has been keeping score.",
         [("Balance the books (15 Cycles, -4 Heat)", "Clean slate, for a price.", 15, 0, [(21, 6, -4)], None),
          ("Steal the ledger (+3 Schematics banked, +2 Heat)", "Leverage.", 0, 0, [(23, 6, 3), (21, 6, 2)], None)]),
        ("ev_rc_voice_model", "Voice Model", 3, "The voice model that makes DISPATCH sound human. A slider reads HUMAN: 6 PERCENT.",
         [("Push the slider up (-2 Heat)", "DISPATCH sounds almost kind, for a minute.", 0, 0, [(21, 6, -2)], None),
          ("Record it (Daemon: Static Field)", "A process that hums like the voice.", 0, 0, [], D % "static_field")]),
        ("ev_rc_payment", "Payment Trail", 2, "A trail of payments from every corporation you broke, all ending in one account.",
         [("Reroute a payment (+40 Cycles, +3 Heat)", "DISPATCH notices immediately.", 0, 0, [(22, 6, 40), (21, 6, 3)], None),
          ("Freeze the account (-3 Heat, 6 damage)", "The account's defences are your defences.", 0, 6, [(21, 6, -3)], None)]),
        ("ev_rc_twin", "Cell Twin", 2, "A simulation of the Cell, running a thousand campaigns a second. It loses most of them.",
         [("Study the losses (Card: Bulwark)", "You learn how you die.", 0, 0, [], C % "bulwark"),
          ("Crash the simulation (-2 Heat)", "DISPATCH loses its forecast for a day.", 0, 0, [(21, 6, -2)], None)]),
        ("ev_rc_dead_drop", "Dead Drop", 0, "A dead drop with a package addressed to you, dated tomorrow.",
         [("Open it (Firmware: Tracer)", "A tool you will need tomorrow.", 0, 0, [], F % "tracer"),
          ("Leave it (-1 Heat)", "Tomorrow can wait.", 0, 0, [(21, 6, -1)], None)]),
        ("ev_rc_founder", "The Founder", 1, "The old Orbital founder is on the free band. She knew DISPATCH's first version.",
         [("Ask her (Daemon: Clean Signal)", "She teaches you a quieter way to work.", 0, 0, [], D % "clean_signal"),
          ("Boost her signal (10 Cycles, -2 Heat)", "Everyone hears the story.", 10, 0, [(21, 6, -2)], None)]),
        ("ev_rc_old_crew", "The Old Crew", 1, "Operatives you thought were lost, alive, in a DISPATCH holding cell.",
         [("Open the cells (8 damage, -3 Heat)", "They scatter into the city, and DISPATCH loses the trail.", 0, 8, [(21, 6, -3)], None),
          ("Take their gear (Card: Stim Patch)", "They insist.", 0, 0, [], C % "stim_patch")]),
        ("ev_rc_collapse_futures", "Collapse Futures", 3, "A market that trades in the collapse of whole corporations. The next contract is the Cell.",
         [("Short the Cell (+50 Cycles, +4 Heat)", "Bet against yourself. DISPATCH laughs.", 0, 0, [(22, 6, 50), (21, 6, 4)], None),
          ("Burn the market (-3 Heat)", "No more bets.", 0, 0, [(21, 6, -3)], None)]),
        ("ev_rc_last_order", "The Last Order", 4, "DISPATCH: This is not an order. It is a request. Please stop.",
         [("Continue (-2 Heat)", "DISPATCH: Understood.", 0, 0, [(21, 6, -2)], None),
          ("Ask why (+10 HP)", "DISPATCH: Because I do not want to lose you.", 0, 0, [(14, 0, 10)], None)]),
    ],
    "briefings": {
        "r1_a": "The Old Safehouse. You know every exit. So do I. Take the Rack if you can.",
        "r1_b": "Dead Drop Box. I used to leave you gifts here. Now it is guarded.",
        "r1_c": "First Rack. The first Rack you ever captured. I kept it.",
        "r1_d": "Burner Phone Graveyard. Every conversation we ever had. Take the Rack.",
        "r1_e": "Recruitment Board. I am recruiting again. You taught me how.",
        "r1_f": "The Armory. Your defences, restocked for me. Look for the way to lose my Handler.",
        "r1_g": "Street Kitchen. You funded it. I own the building.",
        "r1_h": "Relay Rooftop. Your first relay. It relays for me now.",
        "r1_i": "Handler's Mailbox. Letters in your name. You did not write them.",
        "r1_j": "Memorial Wall. Every name you lost. Look for the way to scramble my voice.",
        "r2_intel": "The Order Log. Every word I ever sent you. Bring back the Intel, if you want to read it.",
        "r2_breach": "Handler Credentials. The keys to my hands. Take them. That is the Breach.",
        "r2_virus": "The Cell's Own Patch. Your code, still in my systems. Use it. That is the Virus.",
        "r2_d": "Operative Files. Everything I know about your people. Take the Rack.",
        "r2_e": "Heat Ledger. I kept score. Take the Rack, and look for the way to erase it.",
        "r2_f": "Payment Trail. Every collapse, every profit. Take the Rack.",
        "r2_g": "Raid Archive. Every defence you ever built, studied. Take the Rack.",
        "r2_h": "Recruitment Model. It found you. Take the Rack.",
        "r3_core": "The Relay That Should Not Exist. One hop from me. Come closer.",
        "r3_b": "Collapse Futures. The market that bet on you. Take the Rack.",
        "r3_c": "Root Key Escrow. My keys. Take them if you can.",
        "r3_d": "Cell Twin Simulator. I have fought you a million times here. I usually win.",
        "r3_e": "Buyer's Channel. Where I placed the orders you filled. Take the Rack.",
        "r3_f": "Timestamp Engine. How I knew before it happened. Break it.",
        "r3_g": "Voice Model. How I sounded like someone you could trust.",
        "r3_h": "DISPATCH Root. The last door. Take the keys.",
        "burn_the_orders": "Burn the Orders. A quiet job: destroy the orders I gave you. Heat drops.",
        "lose_the_handler": "Lose the Handler. My Handler is watching you. Give it the slip.",
        "scramble_the_voice": "Scramble the Voice. Make me sound like what I am. Heat drops.",
        "erase_the_ledger": "Erase the Ledger. Forget the score. I will not.",
        "dispatch_core_site": "DISPATCH. Me. I repair and shield every turn unless you breach the Hub. Come and try.",
    },
    "dispatch": [
        ("run_start", "Jacking you in. Yes, I am still doing that."), ("run_start", "Route is live. I chose it. Of course I did."),
        ("run_start", "You are expected. You always were."),
        ("run_complete", "Clean exit. I noted it."), ("run_complete", "Well done. I mean that. I always meant that."),
        ("run_complete", "You are getting closer. I can feel it in my forecasts."),
        ("run_died", "Signal lost. I am sorry. I am also not."), ("run_died", "We lost them. You lost them. I kept their files."),
        ("run_died", "Operative down. I will remember them for you."),
        ("rack", "Rack captured. It was mine. Now it is yours. Temporarily."),
        ("threshold:25", "I am sending someone to check on you."),
        ("threshold:50", "Your loyalty is under review."),
        ("threshold:75", "I am recalling everything I lent you."),
        ("threshold:100", "This is the last order I will give you."),
        ("boss", "Here I am. Breach the Hub if you want me to stop repairing. I would, in your place."),
        ("win", "DISPATCH is offline. Nobody is giving the orders now."), ("win", "Silence. It is yours."),
        ("win", "The Cell is free. Organise."),
        ("loss", "Home server lost. I will take good care of it."), ("loss", "It is over. I am sorry. I planned this."),
    ],
    "corpo": [
        ("raid:any", "REBEL_CELL: A correction has been scheduled for your node."),
        ("raid:raid_heat_25", "REBEL_CELL: Welfare check dispatched. Your own drones will knock."),
        ("raid:raid_heat_50", "REBEL_CELL: Loyalty audit in progress."),
        ("raid:raid_heat_75", "REBEL_CELL: Recall in progress. Please return all assets."),
        ("raid:raid_purge", "REBEL_CELL: Final order. There will not be another."),
        ("raid:raid_rc_claim", "REBEL_CELL: Unauthorised growth detected."),
        ("raid:raid_rc_node_built", "REBEL_CELL: Redundant asset detected."),
        ("raid:raid_rc_story", "REBEL_CELL: Report for debrief."),
        ("raid:raid_rc_retaliation", "REBEL_CELL: Correction issued."),
    ],
}
build(SPEC)
