"""M10: Orbital Commons, the fourth corporation (GDD 8.4 names, DECISIONS 2026-09-24).
Privatised orbital infrastructure: satellite internet, positioning and weather control, the
sky itself enclosed and billed. Its enemies throw Solar Flares (OVERCLOCK your slice: 1.5x on
its next trigger, then it CORRUPTS), orbit their read heads fast and hide behind debris. Its
boss, the Commons Array, shields and repairs itself every turn unless the Hub is breached."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
exec(open(os.path.join(HERE, "gen_corp_lib.py"), encoding="utf-8").read())

C = "res://content/cards/%s.tres"
F = "res://content/firmware/%s.tres"
D = "res://content/daemons/%s.tres"
A = "res://content/assets/%s.tres"

SPEC = {
    "id": "orbital", "name": "Orbital Commons", "unlock_cost": 160,
    "desc": "It owns the sky: every satellite, every signal, every forecast. The commons, by subscription.",
    "comment": "Orbital Commons (M10, GDD 8.4, DECISIONS 2026-09-24): 32-Site Grid in the shared shape; Solar Flares\n"
               "OVERCLOCK the player's slices (1.5x, then CORRUPTED); the Commons Array shields and repairs each turn.",
    "leave_text": "You keep your head down. The sky keeps watching.",
    "slices": [("solar_flare", "Solar Flare", 7, 1, 0, (4, 3, None, {"status": 2, "slice_pick": 1}))],
    "satellite": {"id": "orbital_drone", "name": "Orbital Drone", "desc": "A station-keeping drone that screens its controller."},
    "enemies": [
        {"id": "uplink_relay", "name": "Uplink Relay", "desc": "Throws Solar Flares: your slice burns hot, then corrupts.", "hp": 46,
         "slices": ["atk_9", "solar_flare", "def_6", "crit_14", "atk_9", "miss"], "orbit": 1},
        {"id": "orbital_debris", "name": "Orbital Debris", "desc": "A slab of dead satellite: heavy, hard to turn, resistance 2.", "hp": 62,
         "slices": ["def_8", "atk_10", "def_8", "atk_10", "shield_5", "miss"], "passive": 2},
        {"id": "tracking_station", "name": "Tracking Station", "desc": "Two dishes, two readers: pointers 0 and 15.", "hp": 48,
         "slices": ["atk_8", "atk_8", "def_6", "crit_16", "solar_flare", "miss"], "pointers": (0, 15)},
        {"id": "weather_satellite", "name": "Weather Satellite", "desc": "Fast orbit (4 ticks a turn), self-repair and a flare.", "hp": 44,
         "slices": ["heal_6", "atk_9", "evade_1", "crit_14", "solar_flare", "miss"], "orbit": 4},
        {"id": "ground_control", "name": "Ground Control", "desc": "Hits hard and shields up; its reader drifts 2 a turn.", "hp": 52,
         "slices": ["atk_10", "atk_10", "def_8", "crit_16", "shield_5", "miss"], "orbit": 2},
        {"id": "launch_pad", "name": "Launch Pad", "desc": "Shields, flares and a drone launch every other turn.", "hp": 46,
         "slices": ["shield_5", "atk_8", "shield_5", "solar_flare", "atk_8", "miss"], "spawns": [("orbital_drone", 2, 2, -1, 2)]},
    ],
    "elites": [
        {"id": "station_commander", "name": "Station Commander", "desc": "Two readers, heavy block and a flare.", "hp": 154,
         "slices": ["atk_12", "def_12", "crit_16", "atk_12", "solar_flare", "miss"], "pointers": (0, 15), "passive": 1, "elite": True, "cycle": 35},
        {"id": "geostationary_guard", "name": "Geostationary Guard", "desc": "Orbits 3 a turn, hits like a falling satellite, brings a drone.", "hp": 145,
         "slices": ["shield_8", "atk_14", "solar_flare", "crit_16", "atk_14", "miss"], "orbit": 3, "elite": True, "cycle": 35,
         "spawns": [("orbital_drone", 1, 1, 1, 1)]},
    ],
    "mini_boss": {"id": "mission_director", "name": "Mission Director", "desc": "Orbital Commons flight control, guarding the final Rack.", "hp": 150,
                  "slices": ["atk_10", "def_8", "crit_15", "solar_flare", "shield_5", "miss"], "passive": 2, "elite": True, "mini": True, "cycle": 60,
                  "phases": [{"at": 0.5, "behavior": 1, "ticks": (0, 15), "line": "Go for launch: a second console lights up."},
                             {"at": 0.25, "behavior": 3, "orbit": 3, "line": "Abort window: the readers spin."}]},
    "boss": {"id": "commons_array", "name": "The Commons Array", "desc": "The constellation's brain. It owns the sky and rents it back to you.", "hp": 420,
             "slices": ["atk_14", "solar_flare", "def_12", "crit_24", "atk_14", "miss"], "boss": True, "cycle": 0,
             "hub": {"id": "station_keeping", "name": "Station Keeping", "desc": "Repairs 3 and gains 3 shield each turn unless the Hub is breached.",
                     "effects": [(14, 0, 3), (2, 0, 3)]},
             "phases": [{"at": 0.66, "behavior": 3, "orbit": 4, "ticks": (0, 15), "line": "Orbit change: two readers sweep the sky, fast."},
                        {"at": 0.33, "behavior": 1, "ticks": (0, 10, 20),
                         "wheel": ["crit_24", "solar_flare", "def_12", "crit_24", "atk_14", "miss"],
                         "spawns": [("orbital_drone", 1, 1, -1, 2)],
                         "line": "Full constellation: three readers lock on and the drones deploy."}],
             "comment": "The Commons Array, Orbital Commons final boss (M10, decision 2026-09-24): 420 HP; Station Keeping repairs 3\nand shields 3 per turn unless breached; 66%: two pointers orbiting 4; 33%: three pointers, Crit wheel, 2 drones."},
    "threats": [
        ("lander", "Lander", "Drops in fast: two edges a step toward the highest-value node.", 8, 3, 2, 1, []),
        ("debris_field", "Debris Field", "A slow wall of junk that crushes the weakest node.", 30, 10, 1, 2, []),
        ("signal_jammer", "Signal Jammer", "Jams a link behind it for the rest of the raid.", 18, 6, 1, 0, ["freezes_edges = true"]),
    ],
    "raids": [
        ("raid_orb_heat_25", "Signal Anomaly", 0, 8, [["lander", "lander"]], "raid_heat_25",
         "Orbital Commons has flagged a signal anomaly at your address. Two Landers inbound."),
        ("raid_orb_heat_50", "Spectrum Audit", 0, 12, [["lander", "lander", "signal_jammer"]], "raid_heat_50",
         "An Orbital Commons spectrum audit is sweeping your links. Landers and a Jammer inbound."),
        ("raid_orb_heat_75", "Deorbit Order", 0, 18, [["lander", "signal_jammer", "debris_field", "lockdown_unit"]], "raid_heat_75",
         "Orbital Commons has issued a deorbit order for your network. Debris is falling."),
        ("raid_orb_purge", "Kessler Event", 0, 25, [["lander", "lander", "signal_jammer", "debris_field", "signal_jammer", "debris_field"]], "raid_purge",
         "Orbital Commons is clearing your orbit. Everything it has is falling on you."),
        ("raid_orb_claim", "Unlicensed Transmitter", 1, 8, [["lander"]], "", "A new transmitter without an Orbital licence. A Lander is on the way."),
        ("raid_orb_node_built", "Spectrum Violation", 2, 10, [["debris_field"]], "", "Your new node is broadcasting on a licensed band. Debris incoming."),
        ("raid_orb_story", "Recovery Mission", 3, 12, [["signal_jammer", "debris_field"]], "", "Orbital Commons wants its data back."),
        ("raid_orb_retaliation", "Service Termination", 4, 10, [["icebreaker", "lander"]], "", "Orbital Commons traced the breach and terminated your service."),
    ],
    "home_site": "o_home",
    "t1": [("o1_a", "Ground Station Alpha"), ("o1_b", "Positioning Toll Booth"), ("o1_c", "Rooftop Dish Farm"), ("o1_d", "Subscriber Uplink Office"),
           ("o1_e", "Weather Sales Desk"), ("o1_f", "Launch Scheduling Office"), ("o1_g", "Spectrum Licence Registry"), ("o1_h", "Telemetry Downlink"),
           ("o1_i", "Orbit Insurance Broker"), ("o1_j", "Debris Tracking Radar")],
    "t2": [("o2_intel", "Launch Code Vault", 1), ("o2_breach", "Ground Station Override", 2), ("o2_virus", "Open Spectrum Relay", 3),
           ("o2_d", "Constellation Scheduler", 0), ("o2_e", "Signal Pricing Engine", 0), ("o2_f", "Weather Futures Desk", 0),
           ("o2_g", "Orbital Imaging Archive", 0), ("o2_h", "Spectrum Auction House", 0)],
    "t3": [("o3_core", "Mission Control"), ("o3_b", "Station Keeping Core"), ("o3_c", "Launch Key Escrow"), ("o3_d", "Sky Twin Simulator"),
           ("o3_e", "Board Uplink"), ("o3_f", "Orbital Pricing Authority"), ("o3_g", "Surveillance Constellation"), ("o3_h", "Orbital Root Keystore")],
    "heat_sites": [("scrub_the_downlink", "Scrub the Downlink", 1, -5, "o1_a"), ("spoof_the_positioning", "Spoof the Positioning", 1, -5, "o1_f"),
                   ("jam_the_imaging", "Jam the Imaging", 2, -8, "o1_j"), ("burn_the_orbit_logs", "Burn the Orbit Logs", 3, -8, "o2_e")],
    "boss_site": ("commons_array_site", "The Commons Array"),
    "exploit_names": ("Intel: Launch Codes", "Breach: Ground Station Override", "Virus: Open Spectrum"),
    "paths": [
        ("the_enclosure", "The Enclosure", "Orbital Commons bought the sky. Now the sky has a fee.",
         [("The Enclosure I", 3, "The launch codes include a licence nobody noticed: exclusive rights to every orbit below forty thousand kilometres. The sky was sold in a single signature."),
          ("The Enclosure II", 2, "The ground station override logs show competitors' satellites nudged off station, one by one, for 'debris avoidance'."),
          ("The Enclosure III", 3, "The open spectrum relay has the pricing model: charge for the signal, then charge for the silence when you cut it off.")],
         [("The Enclosure: Amateurs", 1, "An old ham radio club still talks on a free band. Orbital Commons is suing them for the static."),
          ("The Enclosure: Halcyon", 2, "Halcyon Civic's city brain ran on this sky. Orbital Commons kept the deposit when it fell.")],
         "The Commons Array goes dark and the sky goes quiet, then loud: every free band on the planet fills with voices at once.", "", -1),
        ("blackout_weather", "Blackout Weather", "Orbital Commons sells the weather. It can also withhold it.",
         [("Blackout Weather I", 3, "The weather futures desk sells storm forecasts to the highest bidder, a day before anyone else gets them."),
          ("Blackout Weather II", 2, "Districts behind on subscriptions get no storm warnings. The memo calls it service prioritisation."),
          ("Blackout Weather III", 3, "Last spring's flood killed nineteen people in a district with no warning. The forecast existed. Nobody paid for it.")],
         [("Blackout Weather: The Forecast", 0, "Tonight's forecast: a storm over the eastern districts. The eastern districts do not know."),
          ("Blackout Weather: The Bid", 2, "A hedge fund paid four million for tonight's storm. It is betting on the flood.")],
         "The Commons Array falls and every forecast on its servers broadcasts at once, free. The eastern districts board up in time.", "", 1),
        ("gps_tax", "Positioning Tax", "Knowing where you are now costs a subscription.",
         [("Positioning Tax I", 3, "Positioning is metered per request. Ambulances pay per request. So do fire trucks."),
          ("Positioning Tax II", 2, "Unpaid accounts get positions that are close enough. Close enough is fifty metres wrong."),
          ("Positioning Tax III", 3, "The toll booth logs show an ambulance that drove to the wrong street because its account was a day late.")],
         [("Positioning Tax: The Driver", 1, "The ambulance driver keeps a paper map now. She would like to meet the people who made her need it."),
          ("Positioning Tax: The Rate", 2, "The rate doubles in an emergency. Demand is less elastic then, says the model.")],
         "The Commons Array falls and positioning goes free for the whole planet. Every map in the city is suddenly, exactly right.", "", -1),
        ("final_transmission", "Final Transmission", "Somebody has been talking to the Cell from orbit the whole time.",
         [("Final Transmission I", 3, "DISPATCH's signal does not come from the city. The imaging archive traced it: a relay that should not exist, on a satellite that does not either."),
          ("Final Transmission II", 3, "The satellite was launched on an order paid before it was placed. The same account. The same impossible timestamps."),
          ("Final Transmission III", 3, "The satellite's only payload is a listening post. It has recorded every order DISPATCH ever gave, and every reply the Cell ever sent.")],
         [("Final Transmission: The Voice", 3, "In the recordings DISPATCH's voice shifts, year by year, from a person to something else. The change is smooth. It was practising."),
          ("Final Transmission: The Profile", 3, "The listening post keeps a profile of the Cell's habits: which nodes you build, which operatives you trust, which Daemons you love. It is building something from you.")],
         "The Commons Array dies, and the satellite that should not exist changes orbit. It is coming home. It has a name for itself: REBEL_CELL.", "rebel_cell", 2),
        ("dead_satellites", "Dead Satellites", "Orbital Commons parks its dead satellites in the orbits its rivals need.",
         [("Dead Satellites I", 3, "Four hundred dead satellites, parked on purpose in the lanes other operators would use. Nobody can launch through them."),
          ("Dead Satellites II", 2, "Deorbiting the junk is cheap. Leaving it is cheaper and keeps the sky closed. The board chose cheaper."),
          ("Dead Satellites III", 3, "The station keeping core can steer every dead satellite at once. Nobody has ever told it to clean up.")],
         [("Dead Satellites: The Clean-up", 0, "A cleanup program sits unfinished in the keeping core. Somebody started it and was told to stop."),
          ("Dead Satellites: The Lanes", 2, "A map of the blocked lanes. Every one belongs to a public agency.")],
         "The Commons Array falls and the keeping core runs the abandoned cleanup. For a week, the night sky rains slow, harmless fire.", "", -1),
        ("the_commons", "The Commons", "Before Orbital Commons, the name meant something else.",
         [("The Commons I", 3, "The company's first charter, forty years old: a public satellite network, owned by nobody, free to all. The name was a promise."),
          ("The Commons II", 2, "The charter was rewritten in a single board meeting. The minutes say only: monetise the commons."),
          ("The Commons III", 0, "The original founders are old now. One of them still broadcasts on the free band, every night, to nobody.")],
         [("The Commons: The Founder", 1, "The founder answers the Cell's call on the first try. She says she has been waiting for someone to ask."),
          ("The Commons: The Charter", 3, "The original charter is still valid. Nobody ever revoked it. They just stopped reading it.")],
         "The Commons Array falls and the founder reads the original charter aloud on every band at once. The sky, for one night, is free again.", "", 0),
    ],
    "events": [
        ("ev_orb_dish", "Rooftop Dish", 0, "A rooftop dish points at a satellite the Cell has never seen. Its panel is open.",
         [("Reroute it (Card: Whirl)", "The dish spins. So does your deck.", 0, 0, [], C % "whirl"),
          ("Strip it for parts (+2 Schematics banked)", "Good copper, better chips.", 0, 0, [(23, 6, 2)], None)]),
        ("ev_orb_positioning", "Positioning Error", 0, "A delivery drone circles, lost: its owner is a day behind on positioning fees.",
         [("Give it a free fix (-1 Heat)", "It finds its way home.", 0, 0, [(21, 6, -1)], None),
          ("Catch it (Asset: Honeypot, 4 damage)", "The drone's beacon makes a fine lure.", 0, 4, [], A % "honeypot_node")]),
        ("ev_orb_forecast", "Storm Forecast", 0, "A leaked storm forecast for tonight. The district it covers does not have a subscription.",
         [("Broadcast it (-2 Heat)", "The district boards up in time.", 0, 0, [(21, 6, -2)], None),
          ("Sell it (+30 Cycles, +3 Heat)", "Someone is betting on the flood.", 0, 0, [(22, 6, 30), (21, 6, 3)], None)]),
        ("ev_orb_ham_radio", "Ham Radio Club", 1, "An old radio club runs on a free band. They trade tricks for company.",
         [("Swap tricks (Daemon: Fail Forward)", "They teach you to make a miss count.", 0, 0, [], D % "fail_forward"),
          ("Share a meal (+12 HP)", "Soup, bad jokes and a very old antenna.", 0, 0, [(14, 0, 12)], None)]),
        ("ev_orb_solar_panel", "Solar Array", 0, "A private solar array feeds a single tower. The block below it is dark.",
         [("Share the power (-2 Heat, 5 damage)", "The array sparks. The block lights up.", 0, 5, [(21, 6, -2)], None),
          ("Tap it (Firmware: Power Cell)", "A shield that charges your RAM.", 0, 0, [], F % "power_cell")]),
        ("ev_orb_licence", "Spectrum Licence", 2, "A blank spectrum licence sits in a printer tray, already signed.",
         [("Fill it in for the Cell (-3 Heat)", "Your traffic is now legal, technically.", 0, 0, [(21, 6, -3)], None),
          ("Sell it (+3 Schematics banked, +2 Heat)", "Licences are rare and expensive.", 0, 0, [(23, 6, 3), (21, 6, 2)], None)]),
        ("ev_orb_debris", "Falling Debris", 0, "A chunk of dead satellite has landed in a courtyard. It is still warm.",
         [("Salvage the shielding (Card: Shield Wall)", "Heavy plating, light card.", 0, 0, [], C % "shield_wall"),
          ("Salvage the transponder (+20 Cycles)", "Someone upstairs will pay for it back.", 0, 0, [(22, 6, 20)], None)]),
        ("ev_orb_imaging", "Imaging Feed", 2, "An orbital imaging feed shows your safehouse roof, in real time.",
         [("Spoof the feed (-3 Heat, 10 Cycles)", "The roof is now a swimming pool.", 10, 0, [(21, 6, -3)], None),
          ("Steal the feed (Card: Lock On)", "Now you see what they see.", 0, 0, [], C % "lock_on")]),
        ("ev_orb_subscriber", "Subscriber Office", 0, "A queue of people waits to beg for their signal back. The office has one clerk and no chairs.",
         [("Restore a few accounts (-2 Heat, 4 damage)", "The system fights you. A few families get their signal back.", 0, 4, [(21, 6, -2)], None),
          ("Take the clerk's badge (Card: Short Circuit)", "The badge opens the Hub for a moment.", 0, 0, [], C % "short_circuit")]),
        ("ev_orb_launch", "Launch Window", 1, "A launch is scheduled in an hour. The payload manifest has room for one more.",
         [("Add a Cell payload (-2 Heat, 15 Cycles)", "Something of yours is going up.", 15, 0, [(21, 6, -2)], None),
          ("Sabotage the launch (+3 Heat, +3 Schematics banked)", "The rocket does not go up. The insurance pays out.", 0, 0, [(21, 6, 3), (23, 6, 3)], None)]),
        ("ev_orb_telemetry", "Telemetry Burst", 0, "A telemetry downlink spills raw data across the floor of a server room.",
         [("Read it (Daemon: Cascade)", "Patterns within patterns.", 0, 0, [], D % "cascade"),
          ("Sell it (+25 Cycles, +1 Heat)", "Data sells by the byte.", 0, 0, [(22, 6, 25), (21, 6, 1)], None)]),
        ("ev_orb_dispatch_signal", "DISPATCH: Signal", 4, "DISPATCH: Your uplink has been rerouted through a relay the Cell does not own. It is faster. Do not look up.",
         [("Use the relay (-3 Heat)", "DISPATCH: Good.", 0, 0, [(21, 6, -3)], None),
          ("Trace the relay (+2 Heat)", "DISPATCH: That is not necessary. Continue.", 0, 0, [(21, 6, 2)], None)]),
        ("ev_orb_listening_post", "Listening Post", 3, "A rooftop antenna aimed at a patch of empty sky. It is receiving.",
         [("Listen (Daemon: Adrenal Loop, 6 damage)", "The signal gets into your head. It helps.", 0, 6, [], D % "adrenal_loop"),
          ("Cut the cable (-2 Heat)", "The empty sky goes quiet.", 0, 0, [(21, 6, -2)], None)]),
        ("ev_orb_insurance", "Orbit Insurance", 2, "An orbit insurance policy covers a satellite that crashed on purpose. The claim is pending.",
         [("Void the claim (-2 Heat)", "One less fraud.", 0, 0, [(21, 6, -2)], None),
          ("Redirect the payout (+35 Cycles, +3 Heat)", "Somebody has to collect.", 0, 0, [(22, 6, 35), (21, 6, 3)], None)]),
        ("ev_orb_radar", "Debris Radar", 0, "A debris radar tracks everything in the sky. It has a blind spot the size of a satellite.",
         [("Widen the blind spot (-2 Heat)", "Now it misses the Cell too.", 0, 0, [(21, 6, -2)], None),
          ("Borrow its targeting (Asset: Railgun)", "It tracks threats very well.", 0, 3, [], A % "railgun")]),
        ("ev_orb_auction", "Spectrum Auction", 2, "A spectrum auction is live. The reserve price is a public school's annual budget.",
         [("Crash the auction (+2 Heat, Card: Overload)", "The auction servers melt.", 0, 0, [(21, 6, 2)], C % "overload"),
          ("Bid the minimum (20 Cycles, -3 Heat)", "Nobody else bids on a band this cheap.", 20, 0, [(21, 6, -3)], None)]),
        ("ev_orb_founder", "The Founder", 1, "An old woman broadcasts the original Orbital charter on a free band, to nobody.",
         [("Answer her (Card: Nudge Driver)", "She shows you an old engineer's trick.", 0, 0, [], C % "overclock_nudges"),
          ("Boost her signal (-2 Heat, 10 Cycles)", "For an hour, the whole city hears her.", 10, 0, [(21, 6, -2)], None)]),
        ("ev_orb_ground_station", "Ground Station", 0, "A ground station runs unattended. Its keeper left a thermos and the door code on a sticky note.",
         [("Borrow the uplink (+2 Schematics banked)", "Bandwidth, rerouted.", 0, 0, [(23, 6, 2)], None),
          ("Leave a gift (Daemon: Salvager)", "A little process that picks up after you.", 0, 0, [], D % "salvager")]),
        ("ev_orb_signal_price", "Signal Pricing", 2, "The signal pricing engine raises prices whenever it detects an emergency.",
         [("Freeze the prices (-3 Heat, 5 damage)", "The engine fights, then freezes.", 0, 5, [(21, 6, -3)], None),
          ("Short the prices (+30 Cycles, +2 Heat)", "Buy low, sell to Orbital.", 0, 0, [(22, 6, 30), (21, 6, 2)], None)]),
        ("ev_orb_night_sky", "Night Sky", 0, "The clouds part. For once you can see the satellites, crawling like ants across the dark.",
         [("Count them (+8 HP)", "It is calming, in a terrible way.", 0, 0, [(14, 0, 8)], None),
          ("Map their gaps (Card: Tailspin)", "Everyone has blind spots.", 0, 0, [], C % "tailspin")]),
    ],
    "briefings": {
        "o1_a": "Ground Station Alpha. Every signal in the district passes through its dishes. Take the Rack.",
        "o1_b": "Positioning Toll Booth. Where Orbital Commons meters where you are. Take the Rack and the map goes free.",
        "o1_c": "Rooftop Dish Farm. A hundred dishes on one roof, all watching. Blind them.",
        "o1_d": "Subscriber Uplink Office. Where the signal is sold and cut. Take the Rack.",
        "o1_e": "Weather Sales Desk. Tomorrow's storm, sold to the highest bidder. Take the Rack.",
        "o1_f": "Launch Scheduling Office. Every launch on the planet waits for this office. Look for the spoof path.",
        "o1_g": "Spectrum Licence Registry. Who is allowed to speak, and on what band. Take the Rack.",
        "o1_h": "Telemetry Downlink. The constellation's heartbeat. Take the Rack.",
        "o1_i": "Orbit Insurance Broker. Every crash insured twice. Take the Rack.",
        "o1_j": "Debris Tracking Radar. It tracks the junk, and the Cell. Look for the imaging path.",
        "o2_intel": "Launch Code Vault. The codes that steer the constellation. Bring back the Intel.",
        "o2_breach": "Ground Station Override. One console that can move any dish. Take it. That is the Breach.",
        "o2_virus": "Open Spectrum Relay. Orbital Commons locked the spectrum. Unlock it. That is the Virus.",
        "o2_d": "Constellation Scheduler. It decides which satellite looks where. Take the Rack.",
        "o2_e": "Signal Pricing Engine. It raises prices in emergencies. Take the Rack, and look for the orbit logs.",
        "o2_f": "Weather Futures Desk. Orbital Commons bets on disasters it can see coming. Take the Rack.",
        "o2_g": "Orbital Imaging Archive. Every roof in the city, photographed every hour. Take the Rack.",
        "o2_h": "Spectrum Auction House. The sky, sold by the megahertz. Take the Rack.",
        "o3_core": "Mission Control. One hop from the Array. Heavy security, heavier Rack.",
        "o3_b": "Station Keeping Core. It steers every satellite, living and dead. Take it.",
        "o3_c": "Launch Key Escrow. The master keys to the constellation. Take them.",
        "o3_d": "Sky Twin Simulator. A copy of the sky, where Orbital Commons rehearses its outages. Break it.",
        "o3_e": "Board Uplink. The board's private channel to orbit. Listen in, then take the Rack.",
        "o3_f": "Orbital Pricing Authority. What the planet pays for its sky. Take it.",
        "o3_g": "Surveillance Constellation. The satellites that watch the Cell. Blind them.",
        "o3_h": "Orbital Root Keystore. The keys the Array trusts. Take them.",
        "scrub_the_downlink": "Scrub the Downlink. A quiet job: clean the Cell out of the telemetry. Heat drops.",
        "spoof_the_positioning": "Spoof the Positioning. Put the Cell somewhere it is not. Heat drops.",
        "jam_the_imaging": "Jam the Imaging. The satellites stop looking at your roof.",
        "burn_the_orbit_logs": "Burn the Orbit Logs. Every record of the Cell's signals, deorbited.",
        "commons_array_site": "The Commons Array. It owns the sky. It repairs and shields every turn. Breach the Hub, then cut.",
    },
    "dispatch": [
        ("run_start", "Jacking you in. The sky is watching; give it nothing to see."), ("run_start", "Uplink is live. Keep it short."),
        ("run_start", "Orbital traffic is heavy tonight. Good cover."),
        ("run_complete", "Clean exit. The constellation lost you somewhere over the river."), ("run_complete", "Out and clear. Well done."),
        ("run_complete", "Signal received. The Cell thanks you."),
        ("run_died", "Signal lost. Orbital Commons has closed the operative's account."), ("run_died", "We lost them. Regroup."),
        ("run_died", "Operative down. The sky did not blink."),
        ("rack", "Rack captured. Bank it before the next pass."),
        ("threshold:25", "Orbital Commons has flagged a signal anomaly. Expect landers."),
        ("threshold:50", "Spectrum audit in progress. The constellation is counting your links."),
        ("threshold:75", "Deorbit order issued. Debris is falling on the Cell."),
        ("threshold:100", "Orbital Commons is clearing our orbit. Everything is coming down."),
        ("boss", "The Commons Array. It repairs and shields every turn. Breach the Hub, then cut."),
        ("win", "The Commons Array is down. The sky is quiet."), ("win", "Orbital Commons is offline. The free bands are filling up."),
        ("win", "Orbit cleared. There is one more signal up there. It is not ours."),
        ("loss", "Home server lost. Orbital Commons has deorbited the Cell."), ("loss", "We are off the air. Fall back."),
    ],
    "corpo": [
        ("raid:any", "ORBITAL COMMONS: Your service is under review. Please keep your antenna pointed skyward."),
        ("raid:raid_heat_25", "ORBITAL COMMONS: A signal anomaly has been detected at your location. Landers have been dispatched."),
        ("raid:raid_heat_50", "ORBITAL COMMONS: A spectrum audit is under way. Please do not transmit."),
        ("raid:raid_heat_75", "ORBITAL COMMONS: A deorbit order has been issued for your network."),
        ("raid:raid_purge", "ORBITAL COMMONS: Your orbit is being cleared. Thank you for choosing Orbital Commons."),
        ("raid:raid_orb_claim", "ORBITAL COMMONS: An unlicensed transmitter has been detected."),
        ("raid:raid_orb_node_built", "ORBITAL COMMONS: A spectrum violation has been logged against your node."),
        ("raid:raid_orb_story", "ORBITAL COMMONS: We are recovering our data. Please stand clear."),
        ("raid:raid_orb_retaliation", "ORBITAL COMMONS: Your service has been terminated."),
    ],
}
build(SPEC)
