"""M9: Halcyon Civic, the third corporation (GDD 8.4 names, DECISIONS 2026-09-24).
Smart-city services contractor: water, power, transit and policing-as-a-service. Its
enemies issue Citations (a PARASITE on your slice: half output until cleansed), heal and
shield each other, and watch with evasive surveillance masts. Its boss, the Civic Core,
heals and blocks every turn unless the Hub is breached."""
import os
HERE = os.path.dirname(os.path.abspath(__file__))
exec(open(os.path.join(HERE, "gen_corp_lib.py"), encoding="utf-8").read())

C = "res://content/cards/%s.tres"
F = "res://content/firmware/%s.tres"
D = "res://content/daemons/%s.tres"
A = "res://content/assets/%s.tres"

SPEC = {
    "id": "halcyon", "name": "Halcyon Civic", "unlock_cost": 140,
    "desc": "The contractor that runs the city: water, power, transit and the police, billed per resident.",
    "comment": "Halcyon Civic (M9, GDD 8.4, DECISIONS 2026-09-24): 32-Site Grid in the Solace/Meridian shape; Citations\n"
               "plant PARASITE on the player's slices; the Civic Core heals and blocks each turn unless breached.",
    "leave_text": "You keep walking. The streetlights follow you.",
    "slices": [("citation", "Citation", 7, 1, 0, (4, 3, None, {"status": 4, "slice_pick": 1}))],
    "satellite": {"id": "civic_drone", "name": "Civic Drone", "desc": "A Halcyon enforcement drone that shields its officer."},
    "enemies": [
        {"id": "parking_warden", "name": "Parking Warden", "desc": "Writes Citations: your slice runs at half until you cleanse it.", "hp": 48,
         "slices": ["atk_9", "citation", "def_6", "crit_14", "atk_9", "miss"]},
        {"id": "utility_meter", "name": "Utility Meter", "desc": "Heals itself on the public dime. Resistance 1.", "hp": 56,
         "slices": ["def_8", "heal_6", "atk_10", "heal_6", "def_8", "miss"], "passive": 1},
        {"id": "transit_controller", "name": "Transit Controller", "desc": "Two readers on a slow loop: pointers 0 and 15 orbit 1 a turn.", "hp": 50,
         "slices": ["atk_8", "atk_8", "def_6", "crit_14", "atk_8", "miss"], "pointers": (0, 15), "orbit": 1},
        {"id": "surveillance_mast", "name": "Surveillance Mast", "desc": "Hard to pin down: Evade slices and an orbiting read head.", "hp": 44,
         "slices": ["evade_1", "atk_9", "evade_1", "crit_14", "citation", "miss"], "orbit": 2},
        {"id": "patrol_unit", "name": "Patrol Unit", "desc": "Policing-as-a-service. Hits hard, shields up.", "hp": 54,
         "slices": ["atk_10", "atk_10", "def_8", "crit_16", "shield_5", "miss"]},
        {"id": "permit_office", "name": "Permit Office", "desc": "Shields, Citations and a civic drone every other turn.", "hp": 46,
         "slices": ["shield_5", "atk_8", "shield_5", "citation", "atk_8", "miss"], "spawns": [("civic_drone", 2, 2, -1, 2)]},
    ],
    "elites": [
        {"id": "riot_control", "name": "Riot Control", "desc": "Two readers, heavy block and a Citation for everyone.", "hp": 142,
         "slices": ["atk_12", "def_12", "crit_16", "atk_12", "citation", "miss"], "pointers": (0, 15), "passive": 1, "elite": True, "cycle": 35},
        {"id": "zoning_board", "name": "Zoning Board", "desc": "Shields, heals and rezones its read head 2 ticks a turn.", "hp": 132,
         "slices": ["shield_8", "atk_12", "citation", "crit_16", "heal_6", "miss"], "orbit": 2, "elite": True, "cycle": 35,
         "spawns": [("civic_drone", 1, 1, 1, 1)]},
    ],
    "mini_boss": {"id": "city_manager", "name": "City Manager", "desc": "Halcyon's local administrator, guarding the final Rack.", "hp": 150,
                  "slices": ["atk_10", "def_8", "crit_15", "citation", "heal_6", "miss"], "passive": 2, "elite": True, "mini": True, "cycle": 60,
                  "phases": [{"at": 0.5, "behavior": 1, "ticks": (0, 15), "line": "Emergency session: a second reader joins the council."},
                             {"at": 0.25, "behavior": 3, "orbit": 2, "line": "Recess cancelled: the readers wander."}]},
    "boss": {"id": "civic_core", "name": "The Civic Core", "desc": "Halcyon's city brain. It keeps the lights on, and the bill running.", "hp": 360,
             "slices": ["atk_14", "citation", "def_12", "crit_24", "atk_14", "miss"], "boss": True, "cycle": 0,
             "hub": {"id": "emergency_powers", "name": "Emergency Powers", "desc": "Heals 4 and gains 4 block each turn unless the Hub is breached.",
                     "effects": [(14, 0, 4), (1, 0, 4)]},
             "phases": [{"at": 0.66, "behavior": 1, "ticks": (0, 10, 20), "line": "State of emergency: three readers watch the district."},
                        {"at": 0.33, "behavior": 3, "orbit": 2, "ticks": (0, 15),
                         "wheel": ["crit_24", "citation", "def_12", "crit_24", "atk_14", "miss"],
                         "spawns": [("civic_drone", 1, 1, -1, 2)],
                         "line": "Martial services: the readers drift, the drones launch, everything is a crit."}],
             "comment": "The Civic Core, Halcyon final boss (M9, decision 2026-09-24): 360 HP; Emergency Powers heals 4 and\nblocks 4 per turn unless breached; 66%: three pointers; 33%: orbit 2 (two pointers), Crit wheel, 2 drones."},
    "threats": [
        ("inspector", "Inspector", "Quick and thorough: two edges a step toward the highest-value node.", 10, 4, 2, 1, []),
        ("bailiff", "Bailiff", "An armoured repossession unit that goes for the weakest node.", 30, 10, 1, 2, []),
        ("tow_truck", "Tow Truck", "Seals a link behind it for the rest of the raid.", 18, 6, 1, 0, ["freezes_edges = true"]),
    ],
    "raids": [
        ("raid_hal_heat_25", "Code Violation", 0, 8, [["inspector", "inspector"]], "raid_heat_25",
         "Halcyon has logged a code violation at your address. Two Inspectors inbound."),
        ("raid_hal_heat_50", "Compliance Sweep", 0, 12, [["inspector", "inspector", "tow_truck"]], "raid_heat_50",
         "A Halcyon compliance sweep is working your block. Inspectors and a Tow Truck inbound."),
        ("raid_hal_heat_75", "Eviction Order", 0, 18, [["inspector", "tow_truck", "bailiff", "lockdown_unit"]], "raid_heat_75",
         "Halcyon has signed an eviction order. Bailiffs are coming."),
        ("raid_hal_purge", "Urban Renewal", 0, 25, [["inspector", "inspector", "tow_truck", "bailiff", "tow_truck", "bailiff"]], "raid_purge",
         "Halcyon has scheduled your district for urban renewal. Everything it has is coming."),
        ("raid_hal_claim", "Unlicensed Premises", 1, 8, [["inspector"]], "", "A new node without a Halcyon licence. An Inspector is on the way."),
        ("raid_hal_node_built", "Building Permit Denied", 2, 10, [["bailiff"]], "", "Halcyon has denied your building permit. A Bailiff will enforce it."),
        ("raid_hal_story", "Public Interest Order", 3, 12, [["tow_truck", "bailiff"]], "", "Halcyon has declared you a matter of public interest."),
        ("raid_hal_retaliation", "Civil Penalty", 4, 10, [["icebreaker", "inspector"]], "", "Halcyon traced the breach and issued a civil penalty."),
    ],
    "home_site": "h_home",
    "t1": [("h1_a", "Parking Enforcement Office"), ("h1_b", "Water Meter Grid"), ("h1_c", "Streetlight Mesh"), ("h1_d", "Resident Services Desk"),
           ("h1_e", "Transit Fare Gates"), ("h1_f", "Waste Routing Depot"), ("h1_g", "Noise Complaint Registry"), ("h1_h", "Permit Queue Server"),
           ("h1_i", "Utility Shutoff Scheduler"), ("h1_j", "Camera Maintenance Yard")],
    "t2": [("h2_intel", "Council Minutes Archive", 1), ("h2_breach", "Emergency Override Authority", 2), ("h2_virus", "Open Data Portal", 3),
           ("h2_d", "Predictive Patrol Model", 0), ("h2_e", "Resident Credit Bureau", 0), ("h2_f", "Water Rights Exchange", 0),
           ("h2_g", "Transit Signal Control", 0), ("h2_h", "Contract Billing Ledger", 0)],
    "t3": [("h3_core", "Civic Operations Centre"), ("h3_b", "Zoning Futures Desk"), ("h3_c", "Override Key Escrow"), ("h3_d", "City Twin Simulator"),
           ("h3_e", "Council Backchannel"), ("h3_f", "Municipal Pricing Authority"), ("h3_g", "Citizen Profile Archive"), ("h3_h", "Halcyon Root Registry")],
    "heat_sites": [("wipe_the_citations", "Wipe the Citations", 1, -5, "h1_a"), ("blind_the_cameras", "Blind the Cameras", 1, -5, "h1_f"),
                   ("lose_the_case_file", "Lose the Case File", 2, -8, "h1_j"), ("pardon_the_district", "Pardon the District", 3, -8, "h2_e")],
    "boss_site": ("civic_core_site", "The Civic Core"),
    "exploit_names": ("Intel: Council Minutes", "Breach: Emergency Override", "Virus: Open Data Leak"),
    "paths": [
        ("water_rights", "Water Rights", "Halcyon owns the city's water now. The price follows the weather, and the weather follows the price.",
         [("Water Rights I", 3, "The council minutes show the vote: water sold to Halcyon for one credit, with a clause that lets it set the price by postcode."),
          ("Water Rights II", 2, "The emergency override can shut off a street's water in four seconds. The log shows it used forty times this year, always on streets behind on rent."),
          ("Water Rights III", 3, "The open data portal leaks a model: raise prices when it is hottest, because demand cannot fall. The model's name is Thirst.")],
         [("Water Rights: The Pumps", 0, "Pump station nine is manual. Someone could open it by hand. Someone would need to know where it is."),
          ("Water Rights: Meridian", 2, "Meridian Freight Systems hauls bottled water into the districts Halcyon cuts off. They split the margin.")],
         "The Civic Core goes dark and every valve in the city fails open. For one hot week, the water is free.", "", -1),
        ("predictive_policing", "Predictive Policing", "Halcyon's patrol model sends police where it expects crime. It expects crime where it sends police.",
         [("Predictive Policing I", 3, "The patrol model's training data is its own arrest records. It has been learning from itself for six years."),
          ("Predictive Policing II", 2, "Patrol units earn Halcyon a fee per stop. The model is tuned for stops, not safety. The memo calls it throughput."),
          ("Predictive Policing III", 0, "The model has a list of names it calls pre-offenders. Three of them are Cell operatives. One of them is nine years old.")],
         [("Predictive Policing: The Heatmap", 3, "Red squares on a city map. Every red square is a poor block. Every poor block is red."),
          ("Predictive Policing: Quotas", 2, "Stop quotas rise every quarter. Nobody at Halcyon has ever asked what the stops are for.")],
         "The Civic Core falls and the patrol model forgets every name on its list. For a month, nobody is a pre-offender.", "", 1),
        ("transit_blackout", "Transit Blackout", "Halcyon cuts transit to districts that protest. The official reason is maintenance.",
         [("Transit Blackout I", 3, "The signal control logs show maintenance windows that match every protest in the last year, to the minute."),
          ("Transit Blackout II", 2, "The emergency override has a mode called CONTAIN. It stops every train into a district and opens the doors on none."),
          ("Transit Blackout III", 3, "The open data portal publishes the protest schedule to Halcyon before the protesters post it. Someone inside is selling it.")],
         [("Transit Blackout: The Driver", 1, "A tram driver kept her doors open during a CONTAIN. She was fired the next day. She would like a word with the Cell."),
          ("Transit Blackout: The Schedule", 0, "Next week's maintenance windows are already set. They match a march nobody has announced yet.")],
         "The Civic Core crashes and every tram in the city runs its whole route, doors open, lights on. Nobody pays.", "", -1),
        ("the_census", "The Census", "Halcyon ran the census. Someone else read it first.",
         [("The Census I", 3, "The census data was copied the night it was collected. The copy went to an account with no name and no owner."),
          ("The Census II", 3, "The same account paid for Meridian freight that never shipped and Solace stock the day it crashed. It pays before it orders."),
          ("The Census III", 3, "The account read the census for one name. It was looking for the leader of a cell that does not officially exist.")],
         [("The Census: Timestamps", 3, "The copy is timestamped a day before the census began. The clocks were not wrong."),
          ("The Census: The Voice", 3, "A recording from the census call centre. A caller asks for the Cell's leader by a name only DISPATCH uses.")],
         "The Civic Core dies. The unnamed account withdraws everything one second later, and sends the Cell a thank-you note it did not sign.", "dispatch", 2),
        ("orbital_uplink", "Orbital Uplink", "Halcyon's city brain runs on a satellite link it does not own.",
         [("Orbital Uplink I", 2, "The Civic Core's uptime is guaranteed by a contract with Orbital Commons. If the link drops, the city drops."),
          ("Orbital Uplink II", 3, "Orbital Commons bills Halcyon per resident per second. Halcyon bills residents per second, plus margin."),
          ("Orbital Uplink III", 2, "The council backchannel has a memo: Orbital Commons wants the city itself as collateral.")],
         [("Orbital Uplink: The Dish", 0, "The uplink dish on the operations centre roof is the size of a house and guarded like a bank."),
          ("Orbital Uplink: Commons", 2, "Orbital Commons calls its satellites public infrastructure. It has never let the public near them.")],
         "The Civic Core falls. Somewhere above the city, an Orbital Commons satellite notes the lost customer and adjusts its orbit toward the Cell.", "orbital", -1),
        ("smart_meters", "Smart Meters", "Every home in the city has a Halcyon meter. Every meter has a microphone.",
         [("Smart Meters I", 3, "The meters measure power and water. The firmware also measures voices, footsteps and how many people sleep in a room."),
          ("Smart Meters II", 2, "Halcyon raises the bill for homes with more people than the lease allows. The meters count them."),
          ("Smart Meters III", 3, "The citizen profile archive has a file on every home. The Cell's safehouse file is thicker than most.")],
         [("Smart Meters: The Patch", 1, "A technician has a firmware patch that deafens the meters. He needs the Cell to push it city-wide."),
          ("Smart Meters: Overcrowding", 2, "The overcrowding surcharge funds the patrol units that evict the overcrowded.")],
         "The Civic Core falls and the meters go deaf all at once. The city is quiet in a way it has not been for years.", "", 0),
    ],
    "events": [
        ("ev_hal_parking_ticket", "Parking Ticket", 0, "A Halcyon parking drone has ticketed your deck. The fine doubles in an hour.",
         [("Contest it (Card: Sanitize)", "The appeal form teaches you how to clean a flagged slice.", 0, 0, [], C % "sanitize"),
          ("Pay it (10 Cycles, -1 Heat)", "Paid. The drone forgets you.", 10, 0, [(21, 6, -1)], None)]),
        ("ev_hal_water_shutoff", "Water Shutoff", 0, "A street's water has been shut off for late payment. The kids are filling bottles at a leaking hydrant.",
         [("Open the valve (-2 Heat, 4 damage)", "The valve is stiff and hot. The water comes back on.", 0, 4, [(21, 6, -2)], None),
          ("Sell the override code (+25 Cycles, +2 Heat)", "Somebody pays well for it.", 0, 0, [(22, 6, 25), (21, 6, 2)], None)]),
        ("ev_hal_streetlight", "Smart Streetlight", 0, "A smart streetlight follows you with its camera. Its maintenance panel is open.",
         [("Blind it (-1 Heat)", "One less eye on the block.", 0, 0, [(21, 6, -1)], None),
          ("Rewire it (Asset: Railgun, 5 damage)", "A streetlight makes a surprisingly good cannon.", 0, 5, [], A % "railgun")]),
        ("ev_hal_resident_desk", "Resident Services", 0, "A Halcyon kiosk offers resident services. A queue of fifty people waits for one working screen.",
         [("Fix the screens (+10 HP from grateful people)", "Somebody hands you a sandwich and a stim.", 0, 0, [(14, 0, 10)], None),
          ("Skim the kiosk (+20 Cycles, +1 Heat)", "Service fees, rerouted.", 0, 0, [(22, 6, 20), (21, 6, 1)], None)]),
        ("ev_hal_eviction", "Eviction Notice", 0, "An eviction notice glows on a door. The family inside has until midnight.",
         [("Void the notice (-3 Heat, 10 Cycles)", "The notice flickers and becomes a welcome mat.", 10, 0, [(21, 6, -3)], None),
          ("Take their spare parts (Card: Armor Plate)", "They insist. You do not argue.", 0, 0, [], C % "armor_plate")]),
        ("ev_hal_council_leak", "Council Leak", 2, "A councillor's aide offers the next vote's minutes, for a price.",
         [("Buy them (20 Cycles, +2 Schematics banked)", "The minutes are worth more than the vote.", 20, 0, [(23, 6, 2)], None),
          ("Expose the aide (-2 Heat)", "Halcyon has one less leak. The Cell has one less friend.", 0, 0, [(21, 6, -2)], None)]),
        ("ev_hal_patrol_stop", "Patrol Stop", 1, "A Halcyon patrol unit has stopped a kid on the corner. Its scanner is pointed at you next.",
         [("Distract it (6 damage, -2 Heat)", "It follows you instead. It hits hard.", 0, 6, [(21, 6, -2)], None),
          ("Steal its firmware (Firmware: Counterstrike)", "It dodges well. Now so do you.", 0, 0, [], F % "counterstrike")]),
        ("ev_hal_permit_queue", "Permit Queue", 0, "The permit queue has four thousand applications. Every one of them is marked PENDING REVIEW.",
         [("Approve a few hundred (-1 Heat)", "A few hundred people can open a shop tomorrow.", 0, 0, [(21, 6, -1)], None),
          ("Sell priority slots (+30 Cycles, +3 Heat)", "Priority has a price.", 0, 0, [(22, 6, 30), (21, 6, 3)], None)]),
        ("ev_hal_transit_gate", "Fare Gate", 0, "A fare gate is stuck open. Commuters flood through, looking over their shoulders.",
         [("Keep it open (-1 Heat)", "The gate stays open all night.", 0, 0, [(21, 6, -1)], None),
          ("Pull its chip (Card: Feather Touch)", "A precise little chip.", 0, 0, [], C % "feather_touch")]),
        ("ev_hal_census_booth", "Census Booth", 3, "An empty census booth. The screen is already filled in, with your name.",
         [("Erase the entry (-2 Heat)", "The screen accepts the change before you touch it.", 0, 0, [(21, 6, -2)], None),
          ("Read the rest (Daemon: Log Wiper)", "Every entry is yours. A process comes with it.", 0, 0, [], D % "log_wiper")]),
        ("ev_hal_dispatch_permit", "DISPATCH: Permit", 4, "DISPATCH: A Halcyon permit has been issued in the Cell's name. It is valid. Do not ask who applied.",
         [("Use the permit (-3 Heat)", "DISPATCH: Good. It will not last.", 0, 0, [(21, 6, -3)], None),
          ("Burn it (+1 Heat)", "DISPATCH: Noted.", 0, 0, [(21, 6, 1)], None)]),
        ("ev_hal_meter_tech", "Meter Technician", 1, "A Halcyon meter technician is eating lunch in his van. His tablet is unlocked.",
         [("Borrow the tablet (Daemon: Shield Cache)", "The tablet has a lot of shielding configs.", 0, 0, [], D % "shield_cache"),
          ("Ask him to look away (15 Cycles, -2 Heat)", "He looks at his sandwich for a long time.", 15, 0, [(21, 6, -2)], None)]),
        ("ev_hal_zoning_map", "Zoning Map", 2, "A zoning map shows your block rezoned as PREMIUM. The residents do not know yet.",
         [("Warn them (-2 Heat)", "The block organises overnight.", 0, 0, [(21, 6, -2)], None),
          ("Sell the map (+3 Schematics banked, +3 Heat)", "Developers pay well for tomorrow's news.", 0, 0, [(23, 6, 3), (21, 6, 3)], None)]),
        ("ev_hal_waste_depot", "Waste Depot", 0, "Halcyon's waste depot sorts the city's trash, including its discarded hardware.",
         [("Dig for parts (Asset: Sentry, 3 damage)", "A sentry turret, only slightly broken.", 0, 3, [], A % "sentry"),
          ("Dig for data (+2 Schematics banked)", "Nobody wipes their drives.", 0, 0, [(23, 6, 2)], None)]),
        ("ev_hal_camera_yard", "Camera Yard", 0, "Crates of replacement cameras, waiting to go up tomorrow.",
         [("Smash them (-2 Heat, 3 damage)", "Glass everywhere. The block stays dark another week.", 0, 3, [(21, 6, -2)], None),
          ("Reflash them (Card: Duck)", "Now they look the other way on cue.", 0, 0, [], C % "duck")]),
        ("ev_hal_noise_registry", "Noise Complaint", 0, "The noise registry has flagged a street party. Patrol units are on the way.",
         [("Delete the complaint (-1 Heat)", "The party goes on.", 0, 0, [(21, 6, -1)], None),
          ("Join the party (+12 HP)", "Somebody hands you water and a good song.", 0, 0, [(14, 0, 12)], None)]),
        ("ev_hal_credit_bureau", "Credit Score", 2, "The resident credit bureau scores everyone. Your score is zero, which is a record.",
         [("Raise the block's scores (-3 Heat, 5 damage)", "The bureau fights back, but a hundred loans clear.", 0, 5, [(21, 6, -3)], None),
          ("Borrow against the glitch (+35 Cycles, +3 Heat)", "Credit is easy when you are nobody.", 0, 0, [(22, 6, 35), (21, 6, 3)], None)]),
        ("ev_hal_signal_control", "Signal Control", 2, "Transit signal control. One command could turn every light green.",
         [("Turn them green (Card: Spin Cycle, +2 Heat)", "The whole city spins for a minute.", 0, 0, [(21, 6, 2)], C % "spin_cycle"),
          ("Leave a backdoor (Daemon: Warm Boot)", "Next time you will be expected.", 0, 0, [], D % "warm_boot")]),
        ("ev_hal_contract_ledger", "Contract Ledger", 2, "Halcyon's contract ledger bills the city for services never delivered.",
         [("Void the fake invoices (-3 Heat)", "The city saves a fortune. Nobody thanks you.", 0, 0, [(21, 6, -3)], None),
          ("Invoice them back (+3 Schematics banked, +2 Heat)", "Halcyon pays its own invoices without reading them.", 0, 0, [(23, 6, 3), (21, 6, 2)], None)]),
        ("ev_hal_orbital_dish", "Uplink Dish", 3, "A Halcyon uplink dish points at the sky. Something up there is listening back.",
         [("Point it at the Cell (Daemon: Static Field, +2 Heat)", "The dish hums. So do you.", 0, 0, [(21, 6, 2)], D % "static_field"),
          ("Unplug it (-2 Heat)", "Somewhere above, a satellite loses a customer.", 0, 0, [(21, 6, -2)], None)]),
    ],
    "briefings": {
        "h1_a": "Parking Enforcement Office. Every ticket in the city is written here. Take the Rack and the drones stop writing.",
        "h1_b": "Water Meter Grid. Halcyon counts every litre. Cut the Rack and the meters read zero for a day.",
        "h1_c": "Streetlight Mesh. The lights are cameras. The cameras are Halcyon. Dim them.",
        "h1_d": "Resident Services Desk. Where complaints go to die. Take the Rack.",
        "h1_e": "Transit Fare Gates. Every commute is a fee. Open the gates.",
        "h1_f": "Waste Routing Depot. Halcyon sorts the city's trash, and its secrets. Look for both.",
        "h1_g": "Noise Complaint Registry. Halcyon's excuse to send patrols anywhere. Quiet it.",
        "h1_h": "Permit Queue Server. Four thousand applications, all pending. Take the Rack.",
        "h1_i": "Utility Shutoff Scheduler. It decides whose lights go out tonight. Reschedule it.",
        "h1_j": "Camera Maintenance Yard. Replacement eyes for the city. Look for the audit path.",
        "h2_intel": "Council Minutes Archive. Every vote, decided before it was cast. Bring back the Intel.",
        "h2_breach": "Emergency Override Authority. The keys to every valve and signal. Copy them. That is the Breach.",
        "h2_virus": "Open Data Portal. Halcyon publishes what it wants you to see. Publish the rest. That is the Virus.",
        "h2_d": "Predictive Patrol Model. It sends police where it expects crime. Take its Rack.",
        "h2_e": "Resident Credit Bureau. Everyone has a score. Take the Rack, and look for the pardon path.",
        "h2_f": "Water Rights Exchange. The city's water, traded like stock. Take the Rack.",
        "h2_g": "Transit Signal Control. Every light, every train, one console. Take it.",
        "h2_h": "Contract Billing Ledger. Halcyon bills the city for everything, twice. Take the Rack.",
        "h3_core": "Civic Operations Centre. One hop from the Civic Core. Heavy security, heavier Rack.",
        "h3_b": "Zoning Futures Desk. Halcyon bets on the blocks it is about to rezone. Take the Rack.",
        "h3_c": "Override Key Escrow. The master keys to the city. Take them.",
        "h3_d": "City Twin Simulator. A copy of the city, where Halcyon rehearses emergencies. Break it.",
        "h3_e": "Council Backchannel. Where the real votes happen. Listen in, then take the Rack.",
        "h3_f": "Municipal Pricing Authority. What the city pays to exist. Take it.",
        "h3_g": "Citizen Profile Archive. A file on every home, including yours. Burn it.",
        "h3_h": "Halcyon Root Registry. The keys the Civic Core trusts. Take them.",
        "wipe_the_citations": "Wipe the Citations. A quiet job: clear the fines that follow the Cell. Heat drops.",
        "blind_the_cameras": "Blind the Cameras. Put the block's cameras to sleep. Heat drops.",
        "lose_the_case_file": "Lose the Case File. Halcyon has a file on the Cell. Misplace it.",
        "pardon_the_district": "Pardon the District. Clear the records of a whole district, the Cell's included.",
        "civic_core_site": "The Civic Core. Halcyon's city brain. It heals and walls up every turn. Breach the Hub, then cut.",
    },
    "dispatch": [
        ("run_start", "Jacking you in. Halcyon watches the streets; stay off them."), ("run_start", "Route is live. Mind the cameras."),
        ("run_start", "City traffic is light tonight. Move quickly."),
        ("run_complete", "Clean exit. Halcyon is filing a report nobody will read."), ("run_complete", "Out and clear. Well done."),
        ("run_complete", "The city sleeps a little easier."),
        ("run_died", "Signal lost. Halcyon has marked the operative as relocated."), ("run_died", "We lost them. Regroup."),
        ("run_died", "Operative down. The city will not notice. We will."),
        ("rack", "Rack captured. Bank it before Halcyon audits the discrepancy."),
        ("threshold:25", "Halcyon has logged a code violation. Expect inspectors."),
        ("threshold:50", "Compliance sweep in progress. Halcyon is counting your nodes."),
        ("threshold:75", "Eviction order signed. Bailiffs are coming."),
        ("threshold:100", "Urban renewal scheduled. Halcyon means to erase the Cell."),
        ("boss", "The Civic Core. It heals and walls up every turn. Breach the Hub, then cut."),
        ("win", "The Civic Core is down. The city runs itself for a day."), ("win", "Halcyon is offline. The lights are still on, somehow."),
        ("win", "Contract terminated. Next target when you are ready."),
        ("loss", "Home server lost. Halcyon has rezoned the Cell out of existence."), ("loss", "We are off the grid. Fall back."),
    ],
    "corpo": [
        ("raid:any", "HALCYON CIVIC: A service request has been opened at your address. Please remain at home."),
        ("raid:raid_heat_25", "HALCYON CIVIC: A code violation has been recorded at your premises. Inspectors have been scheduled."),
        ("raid:raid_heat_50", "HALCYON CIVIC: A compliance sweep is under way. Thank you for your cooperation."),
        ("raid:raid_heat_75", "HALCYON CIVIC: An eviction order has been approved. Please vacate the premises."),
        ("raid:raid_purge", "HALCYON CIVIC: Your district has been scheduled for urban renewal. We appreciate your understanding."),
        ("raid:raid_hal_claim", "HALCYON CIVIC: Unlicensed premises detected. An Inspector will verify your licence."),
        ("raid:raid_hal_node_built", "HALCYON CIVIC: Your building permit has been denied. Enforcement is on its way."),
        ("raid:raid_hal_story", "HALCYON CIVIC: You have been designated a matter of public interest."),
        ("raid:raid_hal_retaliation", "HALCYON CIVIC: A civil penalty has been issued against your account."),
    ],
}
build(SPEC)
